#!/usr/bin/env python3
"""Parse an SM64 geo.inc.c into a DSCE part table (the hand-derived-for-Mario format).

Walks the geo layout from a root symbol: follows GEO_BRANCH, takes the FIRST child of
every GEO_SWITCH_CASE (the default case), collects GEO_ANIMATED_PART nodes in traversal
order (= anim rotation-slot order), tracking parent links through OPEN/CLOSE nesting.
GEO_ROTATION_NODE / GEO_ASM / GEO_SCALE / GEO_DISPLAY_LIST are passed through (a
DISPLAY_LIST directly under an animated part with a NULL dl fills that part's dl).

Usage: gen_geo_parts.py <geo.inc.c> <root_symbol> <table_c_name> <out_inc>
"""
import re
import sys


def parse_layouts(text):
    layouts = {}
    for m in re.finditer(r"const GeoLayout (\w+)\[\] = \{(.*?)\n\};", text, re.S):
        body = []
        for line in m.group(2).splitlines():
            line = line.split("//")[0].strip().rstrip(",")
            if line:
                body.append(line)
        layouts[m.group(1)] = body
    return layouts


def main():
    src, root, cname, out = sys.argv[1:5]
    text = open(src).read()
    layouts = parse_layouts(text)
    parts = []  # (tx,ty,tz,parent,dl)

    def walk(sym, parent):
        nodes = layouts[sym]
        stack = [parent]      # parent part index per nesting depth
        last_new = parent     # the part a following OPEN_NODE attaches children to
        skip_depth = None     # inside a switch: skip all but the first child at that depth
        depth = 0
        seen_at_depth = {}    # depth -> children seen (for switch default-case picking)
        switch_depths = set()
        for line in nodes:
            if line.startswith("GEO_OPEN_NODE"):
                depth += 1
                stack.append(last_new)
                seen_at_depth[depth] = 0
                continue
            if line.startswith("GEO_CLOSE_NODE"):
                seen_at_depth.pop(depth, None)
                switch_depths.discard(depth)
                depth -= 1
                stack.pop()
                last_new = stack[-1]
                continue
            # inside a switch's child list, only the FIRST child (default case) is taken
            if depth in switch_depths:
                seen_at_depth[depth] = seen_at_depth.get(depth, 0) + 1
                if seen_at_depth[depth] > 1:
                    # skip this node entirely; if it opens children, they're skipped by
                    # tracking a blank parent (-2) that emits nothing
                    last_new = -2
                    continue
            if line.startswith("GEO_SWITCH_CASE"):
                switch_depths.add(depth + 1)
                continue
            m = re.match(r"GEO_ANIMATED_PART\(\s*\w+\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(\w+)\s*\)", line)
            if m:
                if stack[-1] == -2:
                    last_new = -2
                    continue
                tx, ty, tz, dl = int(m.group(1)), int(m.group(2)), int(m.group(3)), m.group(4)
                parts.append([tx, ty, tz, stack[-1], None if dl == "NULL" else dl])
                last_new = len(parts) - 1
                continue
            m = re.match(r"GEO_DISPLAY_LIST\(\s*\w+\s*,\s*(\w+)\s*\)", line)
            if m and stack[-1] >= 0 and parts[stack[-1]][4] is None:
                parts[stack[-1]][4] = m.group(1)
                continue
            m = re.match(r"GEO_BRANCH\(\s*\d+\s*,\s*(\w+)\s*\)", line)
            if m and m.group(1) in layouts and stack[-1] != -2:
                walk(m.group(1), stack[-1])
                continue
            # GEO_ROTATION_NODE / GEO_ASM / GEO_SCALE / GEO_SHADOW etc: pass-through;
            # if it owns an OPEN_NODE its children attach to the current parent
            last_new = stack[-1]

    walk(root, -1)
    with open(out, "w") as f:
        f.write(f"/* GENERATED by gen_geo_parts.py from {src.split('/')[-1]} root {root} */\n")
        f.write(f"#define {cname.upper()}_COUNT {len(parts)}\n")
        f.write(f"static const DsceMarioPart {cname}[{len(parts)}] = {{\n")
        for i, (tx, ty, tz, parent, dl) in enumerate(parts):
            f.write(f"    /* {i:2d} */ {{ {tx}, {ty}, {tz}, {parent}, 0, {dl or 'NULL'} }},\n")
        f.write("};\n")
    print(f"gen_geo_parts: {len(parts)} parts -> {out}")


if __name__ == "__main__":
    main()
