#!/usr/bin/env python3
"""Generate dsce_mario_anims.c: SM64 animation data for the Brother's Mask N64 mod.

Reads the sm64 decomp's extracted per-animation sources (assets/anims/anim_XX[_YY].inc.c,
filenames encode the hex anim ids they define) and emits one MM translation unit that
#includes the wanted ones plus a full 209-entry id->Animation* table (positional, C89 —
IDO has no designated initializers).

Usage: gen_mario_anims.py <sm64_anims_dir> <out_c> <id_hex> [<id_hex> ...]

Only invoked from `make mod` (stage-sm64-assets step) — output is generated into the mm
build staging area, never committed, per the both-baseroms-in installation contract.
"""
import os
import re
import sys


def main():
    anims_dir, out_c = sys.argv[1], sys.argv[2]
    wanted = sorted({int(a, 16) for a in sys.argv[3:]})

    # map id -> file that defines it (filenames like anim_56.inc.c, anim_72_73.inc.c)
    id_to_file = {}
    for f in sorted(os.listdir(anims_dir)):
        m = re.match(r"anim((_[0-9A-Fa-f]{2})+)\.inc\.c$", f)
        if not m:
            continue
        for tok in m.group(1).strip("_").split("_"):
            id_to_file.setdefault(int(tok, 16), f)

    files, missing = [], []
    for i in wanted:
        if i in id_to_file:
            if id_to_file[i] not in files:
                files.append(id_to_file[i])
        else:
            missing.append(i)
    if missing:
        sys.exit(f"gen_mario_anims: no anim file for ids {[hex(i) for i in missing]}")

    # which ids does each included file actually define? (a combined file included for one
    # id also defines its siblings -- include them in the table for free)
    defined = set()
    for f in files:
        toks = re.match(r"anim((_[0-9A-Fa-f]{2})+)\.inc\.c$", f).group(1)
        defined.update(int(t, 16) for t in toks.strip("_").split("_"))

    n = 0xD1
    rows = []
    for i in range(n):
        rows.append(f"    anim_{i:02X}," if i in defined else "    0,")

    # IDO (C89) rejects the files' struct-before-arrays ordering (GCC tolerates the
    # implicit reference); inline each file's content REORDERED: arrays first, structs after.
    arrays, structs = [], []
    for f in files:
        src = open(os.path.join(anims_dir, f)).read()
        for m2 in re.finditer(r"static const struct Animation .*?\};", src, re.S):
            structs.append(m2.group(0))
        for m2 in re.finditer(r"static const (?:u16|s16) \w+\[\] = \{.*?\};", src, re.S):
            arrays.append(m2.group(0))

    with open(out_c, "w") as out:
        out.write("/* GENERATED by gen_mario_anims.py -- do not edit, do not commit. */\n")
        out.write('#include "dsce_mario_compat.h"\n\n')
        out.write("\n\n".join(arrays))
        out.write("\n\n")
        out.write("\n\n".join(structs))
        out.write("\n\n/* id -> Animation*; 0 entries fall back to the kernel's fake anim"
                  " (counted). */\n")
        out.write(f"const struct Animation* const gDsceMarioAnimTable[{n}] = {{\n")
        out.write("\n".join(rows))
        out.write("\n};\n")
        out.write(f"const int gDsceMarioAnimTableLen = {n};\n")
    print(f"gen_mario_anims: {len(files)} files, {len(defined)} anims -> {out_c}")


if __name__ == "__main__":
    main()
