/* GENERATED by gen_xtest_arena.py -- the XTEST cross-game arena (mod side).
 * The SAME triangles the sm64-xtest ROM walks; served by the DSCE_XTEST
 * collision shim via SM64's original find_floor/wall algorithms. */
#pragma once

#define DSCE_XTEST_NUM_VERTS 34
static const short sDsceXtestVerts[DSCE_XTEST_NUM_VERTS][3] = {
    { -2400, 0, 400 },
    { -2400, 0, 4600 },
    { 800, 0, 4600 },
    { 800, 0, 400 },
    { -2400, 0, -1000 },
    { -2400, 0, 0 },
    { 800, 0, 0 },
    { 800, 0, -1000 },
    { -2400, 0, -2600 },
    { -2400, 0, -1800 },
    { 800, 0, -1800 },
    { 800, 0, -2600 },
    { -2400, 0, -4000 },
    { -2400, 0, -3400 },
    { 800, 0, -3400 },
    { 800, 0, -4000 },
    { -2400, 0, -5200 },
    { -2400, 0, -4400 },
    { 800, 0, -4400 },
    { 800, 0, -5200 },
    { -2400, -300, -1800 },
    { -2400, -300, -1000 },
    { 800, -300, -1000 },
    { 800, -300, -1800 },
    { 800, 1000, -3400 },
    { -2400, 1000, -3400 },
    { -2400, 350, -4400 },
    { -2400, 350, -4000 },
    { 800, 350, -4000 },
    { 800, 350, -4400 },
    { -2400, 2000, -5200 },
    { -2400, 2000, 4600 },
    { 800, 2000, -5200 },
    { 800, 2000, 4600 },
};
#define DSCE_XTEST_NUM_TRIS 36
/* a, b, c, burning */
static const short sDsceXtestTris[DSCE_XTEST_NUM_TRIS][4] = {
    { 0, 1, 2, 0 },
    { 0, 2, 3, 0 },
    { 4, 5, 6, 0 },
    { 4, 6, 7, 0 },
    { 8, 9, 10, 0 },
    { 8, 10, 11, 0 },
    { 12, 13, 14, 0 },
    { 12, 14, 15, 0 },
    { 16, 17, 18, 0 },
    { 16, 18, 19, 0 },
    { 20, 21, 22, 0 },
    { 20, 22, 23, 0 },
    { 23, 10, 9, 0 },
    { 23, 9, 20, 0 },
    { 21, 4, 7, 0 },
    { 21, 7, 22, 0 },
    { 11, 8, 25, 0 },
    { 11, 25, 24, 0 },
    { 13, 25, 24, 0 },
    { 13, 24, 14, 0 },
    { 26, 27, 28, 0 },
    { 26, 28, 29, 0 },
    { 15, 28, 27, 0 },
    { 15, 27, 12, 0 },
    { 17, 26, 29, 0 },
    { 17, 29, 18, 0 },
    { 16, 30, 31, 0 },
    { 16, 31, 1, 0 },
    { 2, 33, 32, 0 },
    { 2, 32, 19, 0 },
    { 19, 32, 30, 0 },
    { 19, 30, 16, 0 },
    { 1, 31, 33, 0 },
    { 1, 33, 2, 0 },
    { 5, 0, 3, 1 },
    { 5, 3, 6, 1 },
};
#define DSCE_XTEST_WATER_X1 -2400
#define DSCE_XTEST_WATER_Z1 -1800
#define DSCE_XTEST_WATER_X2 800
#define DSCE_XTEST_WATER_Z2 -1000
#define DSCE_XTEST_WATER_Y -60
#define DSCE_XTEST_SPAWN_X -837
#define DSCE_XTEST_SPAWN_Y 0
#define DSCE_XTEST_SPAWN_Z 1881
#define DSCE_XTEST_SPAWN_YAW (-32768)
