/* [DSCE N64] The one CODE-segment hook (called once per frame from Play_Update via the hook-only
 * patch). Spawns the Phase P spike actor on L+R+Z. Lives in code (not the overlay) because the
 * caller must exist before the overlay loads; Actor_Spawn pulls the overlay in. */
#include "global.h"
#include "audiomgr.h"
#include "zelda_arena.h"
#include "dsce_config.h"
#include "dsce_tuning.h" /* generated by make mod: DSCE_TESTBOOT 0/1 */
#include "dsce_n64_abi.h"
#include "dsce_telemetry.h"
#include "overlays/gamestates/ovl_title/z_title.h"

/* Telemetry lives HERE (code segment, fixed VA) not in the overlay: actor overlays are
 * relocated at load time, so an overlay-resident block has no stable address for the
 * emulator peek / hardware notes. The actor (overlay) writes it via extern. Layout is
 * u32 each: magic 'DSCE', frame, tickUs, tickUsMax, arenaFree, arenaFreeMin, action. */
DsceTelemetry gDsceTelemetry = { 0x44534345, 0, 0, 0, 0, 0xFFFFFFFF, 0, 0.0f, 0.0f, 0.0f, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
int gDsceSpikeAlive = 0; /* set by actor Init, cleared by Destroy (scene changes kill actors) */
u32 gDsceProbe[4] = { 0, 0, 0, 0 }; /* debug scratch: read via the plugin's CT_PEEK_ADDR channel */
#if DSCE_DBG_GAMEPLAY
/* Updated from Play_Update, not the takeover actor. This remains live when Actor_UpdateAll
 * suppresses Mario and lets headless boundary tests identify the MM state responsible. */
u32 gDsceLifecycleProbe[8] = { 0, 0, 0, 0, 0, 0, 0, 0 };
#endif

/* [DSCE LOG] Ridiculously-detailed structured logging over a fixed-VA RDRAM ring buffer. The ROM
 * appends records via Dsce_Log(tag, a,b,c,d); the mupen input plugin drains gDsceLogHead each frame
 * and emits one JSONL line per record to logs/<unix_ts>.jsonl (tag + 4 s32 args + game frame). Fixed
 * address (code .data) so the plugin can peek it. gDsceLogHead is the monotonically-increasing write
 * count (NOT wrapped); records live at gDsceLogRing[head % DSCE_LOG_RING]. Enabled by DSCE_LOG. */
#define DSCE_LOG_RING 256 /* 12KB; 1024 ate too much heap (arena-floor ratchet) */
#if DSCE_DBG_LEGACY
typedef struct DsceLogRec {
    u32 seq;     /* == head at write time (monotonic) */
    u32 frame;   /* gDsceTelemetry.frame (actor tick) or the play frame */
    char tag[24];/* event tag, e.g. "xform.808388B8" */
    s32 a, b, c, d; /* numeric args (meaning per-tag) */
} DsceLogRec;
static_assert(sizeof(DsceLogRec) == 48, "legacy log decoder requires 48-byte records");
DsceLogRec gDsceLogRing[DSCE_LOG_RING];
volatile u32 gDsceLogHead = 0; /* total records written; plugin reads this each frame */
#endif
extern u32 gDscePlayFrame;     /* a free-running play frame counter (defined below) */

void Dsce_Log(const char* tag, s32 a, s32 b, s32 c, s32 d) {
#if DSCE_DBG_LEGACY
    DsceLogRec* r = &gDsceLogRing[gDsceLogHead & (DSCE_LOG_RING - 1)];
    s32 i;
    r->seq = gDsceLogHead;
    r->frame = gDscePlayFrame;
    for (i = 0; (i < 23) && (tag[i] != '\0'); i++) {
        r->tag[i] = tag[i];
    }
    r->tag[i] = '\0';
    r->a = a; r->b = b; r->c = c; r->d = d;
    gDsceLogHead++;
    {
        extern void Dsce_Fh(u8, u16, s32, s32, s32, s32);
        Dsce_Fh(0, (u16)((tag[0] << 8) | tag[1]), a, b, c, d);
    }
#else
    (void)tag; (void)a; (void)b; (void)c; (void)d;
#endif
}
u32 gDscePlayFrame = 0;

/* ================= DSCE FIREHOSE (DEBUG ROMs ONLY) =================
 * Judgement-free debugging: a large tagged event ring drained losslessly by the
 * emulator plugin (CT_FH_*) and ingested into ClickHouse (tools/firehose_ingest.py).
 * Ontology domains (numeric; names live in the ingester):
 *   1 audio.request   every SfxRequest the WHOLE game enqueues (polled from
 *                     sSfxRequests -- non-static, no patch needed)
 *   2 audio.seqplayer seq-player-0 health + SFX channel fonts, per frame
 *   3 audio.heap      permanent/cache pool fill levels, per frame
 *   4 audio.pipeline  audio-thread clock, AI DMA registers, PCM energy, scheduler state
 *   5 kernel.action   sandbox action transitions
 *   6 kernel.sound    SM64 soundBits -> msfx resolution (hits AND misses)
 *   7 quest.rite      Song-of-Healing and statue state-machine boundary
 *   0 legacy          every Dsce_Log record, mirrored (tag = first 2 chars) */
#if DSCE_DBG_FIREHOSE
#define DSCE_FH_RING 1024 /* 32KB BSS; debug ROMs only -- arena floor is logged below */
typedef struct DsceFhRec {
    u32 seq;
    u8 domain;
    u8 flags;
    u16 tag;
    u32 tick;  /* sandbox tick (gDsceTelemetry.frame) */
    u32 frame; /* gDscePlayFrame */
    s32 a, b, c, d;
} DsceFhRec; /* 32 bytes; the plugin mirrors this layout */
static_assert(sizeof(DsceFhRec) == 32, "firehose decoder requires 32-byte records");
DsceFhRec gDsceFhRing[DSCE_FH_RING];
volatile u32 gDsceFhHead = 0;
#if DSCE_DBG_AUDIO
typedef struct DsceAiSubmitTrace {
    u32 attempts;
    u32 failures;
    u32 successes;
    s32 lastResult;
    u32 lastBuffer;
    u32 lastSize;
    u32 lastStatus;
    u32 lastLength;
} DsceAiSubmitTrace;
volatile DsceAiSubmitTrace gDsceAiSubmitTrace;
typedef struct DsceAudioMgrTrace {
    u32 timeouts;
    u32 successes;
    u32 exhaustedBursts;
    u32 consecutive;
    u32 maxConsecutive;
} DsceAudioMgrTrace;
volatile DsceAudioMgrTrace gDsceAudioMgrTrace;
typedef struct DsceAudioUpdateTrace {
    u32 phase;
    s32 a;
    s32 b;
    u32 taskCount;
    u32 dmaSubmits;
    u32 lastDmaDevAddr;
    u32 lastDmaSize;
    u32 lastDmaQueue;
} DsceAudioUpdateTrace;
volatile DsceAudioUpdateTrace gDsceAudioUpdateTrace;
typedef struct DsceAudioSeqTrace {
    u32 channel;
    u32 layer;
    s32 layerIndex;
    s32 fontId;
    u32 invalidCount;
    u32 invalidChannelPtr;
    u32 invalidLayer;
    s32 invalidLayerIndex;
    s32 invalidFontId;
    s32 invalidPlayer;
    s32 invalidChannel;
    u32 invalidTask;
    u32 invalidScriptPc;
    s32 invalidDepth;
    s32 invalidValue;
    u32 invalidUnk22;
    u32 invalidDynTable;
    u32 invalidStack[4];
    u32 invalidLayers[4];
    u32 invalidSeqData;
} DsceAudioSeqTrace;
volatile DsceAudioSeqTrace gDsceAudioSeqTrace;
typedef struct DsceAudioSlowLoadTrace {
    u32 calls;
    u32 invalidCount;
    s32 fontId;
    s32 instId;
    u32 sample;
    u32 isDone;
    u32 contextChannel;
    u32 contextPc;
    s32 contextPlayer;
    s32 contextChannelIndex;
    s32 contextPort;
    u32 contextSeqData;
    u32 contextOpcodeWord;
    u32 contextScriptPc;
    s32 contextValue;
    s32 contextDepth;
    u32 contextUnk22;
    u32 contextDynTable;
    u32 contextLayers[4];
    s32 invalidFontId;
    s32 invalidInstId;
    u32 invalidSample;
    u32 invalidIsDone;
    u32 invalidContextChannel;
    u32 invalidContextPc;
    s32 invalidContextPlayer;
    s32 invalidContextChannelIndex;
    s32 invalidContextPort;
    u32 invalidContextSeqData;
    u32 invalidContextOpcodeWord;
    u32 invalidContextScriptPc;
    s32 invalidContextValue;
    s32 invalidContextDepth;
    u32 invalidContextUnk22;
    u32 invalidContextDynTable;
    u32 invalidContextLayers[4];
} DsceAudioSlowLoadTrace;
volatile DsceAudioSlowLoadTrace gDsceAudioSlowLoadTrace;
typedef struct DsceAudioChannelPtrTrace {
    u32 count;
    s32 player;
    s32 slot;
    u32 badPtr;
    u32 task;
    u32 seqData;
    u32 miscStart;
    u32 miscCur;
    u32 channels[16];
    u32 scriptPc;
    s32 depth;
    s32 value;
    u32 seqId;
    u32 stack[4];
    u32 sourceRa;
    s32 matchingLayer;
    u32 matchingLayerPc;
    u32 matchingLayerNote;
} DsceAudioChannelPtrTrace;
volatile DsceAudioChannelPtrTrace gDsceAudioChannelPtrTrace;

/* Audio-thread flight recorder. Unlike the per-frame firehose snapshots, this preserves the
 * exact sequence instructions immediately preceding the first detected fault. The recorder
 * freezes at that boundary so a later crash or a slow frontend capture cannot overwrite the
 * causal history. It is read directly from RDRAM by run_debug_release.py; no emulator changes. */
#define DSCE_SEQ_FLIGHT_RING 1024
typedef enum DsceSeqFlightKind {
    DSCE_SEQ_FLIGHT_CHANNEL_OPCODE = 1,
    DSCE_SEQ_FLIGHT_PLAYER_OPCODE = 2,
    DSCE_SEQ_FLIGHT_SEQUENCE_WRITE = 3,
    DSCE_SEQ_FLIGHT_BAD_STOPCHAN = 4,
    DSCE_SEQ_FLIGHT_BAD_SLOWLOAD = 5,
    DSCE_SEQ_FLIGHT_SEQUENCE_LOAD = 6,
    DSCE_SEQ_FLIGHT_DMA_OVERLAP = 7,
    DSCE_SEQ_FLIGHT_BAD_POINTER = 8,
} DsceSeqFlightKind;
typedef struct DsceSeqFlightRec {
    u32 seq;
    u32 task;
    u32 frame;
    u32 meta; /* kind|player|channel|opcode, one byte each */
    u32 pc;
    u32 seqData;
    s32 a;
    s32 b;
} DsceSeqFlightRec; /* 32 bytes; mirrored by run_debug_release.py */
static_assert(sizeof(DsceSeqFlightRec) == 32,
              "sequence flight decoder requires 32-byte records");
volatile DsceSeqFlightRec gDsceSeqFlightRing[DSCE_SEQ_FLIGHT_RING];
volatile u32 gDsceSeqFlightHead = 0;
volatile u32 gDsceSeqFlightFrozen = 0;

static u32 Dsce_SeqFlightSequenceSize(SequencePlayer* seqPlayer) {
    u32 seqId;

    if ((seqPlayer == NULL) || (seqPlayer->seqData == NULL) ||
        (seqPlayer->seqId >= gAudioCtx.sequenceTable->header.numEntries)) {
        return 0;
    }
    seqId = seqPlayer->seqId;
    if (gAudioCtx.sequenceTable->entries[seqId].size == 0) {
        seqId = gAudioCtx.sequenceTable->entries[seqId].romAddr;
    }
    return gAudioCtx.sequenceTable->entries[seqId].size;
}

static void Dsce_SeqFlightRecord(u8 kind, SequencePlayer* seqPlayer, SequenceChannel* channel,
                                 u8 opcode, void* pc, s32 a, s32 b) {
    volatile DsceSeqFlightRec* rec;
    u32 seq;
    u8 player = 0xFF;
    u8 channelIndex = 0xFF;

    if (gDsceSeqFlightFrozen != 0) {
        return;
    }
    if (seqPlayer != NULL) {
        player = seqPlayer->playerIndex;
    }
    if (channel != NULL) {
        channelIndex = channel->channelIndex;
    }
    seq = gDsceSeqFlightHead;
    rec = &gDsceSeqFlightRing[seq & (DSCE_SEQ_FLIGHT_RING - 1)];
    rec->seq = seq;
    rec->task = gAudioCtx.totalTaskCount;
    rec->frame = gDscePlayFrame;
    rec->meta = ((u32)kind << 24) | ((u32)player << 16) | ((u32)channelIndex << 8) | opcode;
    rec->pc = (u32)pc;
    rec->seqData = (seqPlayer != NULL) ? (u32)seqPlayer->seqData : 0;
    rec->a = a;
    rec->b = b;
    gDsceSeqFlightHead = seq + 1;
}

static u32 Dsce_SeqFlightOpcodeWord(SequencePlayer* seqPlayer, u8* pc) {
    u32 size = Dsce_SeqFlightSequenceSize(seqPlayer);
    u32 offset;

    if ((seqPlayer == NULL) || (pc == NULL) || (pc < seqPlayer->seqData)) {
        return 0;
    }
    offset = pc - seqPlayer->seqData;
    if ((offset + 4) > size) {
        return 0;
    }
    return ((u32)pc[0] << 24) | ((u32)pc[1] << 16) | ((u32)pc[2] << 8) | pc[3];
}

void Dsce_AudioSeqOpcodeTrace(void* channelPtr, void* pc, s32 opcode) {
    SequenceChannel* channel = channelPtr;
    SequencePlayer* seqPlayer = channel->seqPlayer;
    u32 state = ((u32)channel->scriptState.depth << 24) |
                ((u32)(u8)channel->scriptState.value << 16) | channel->delay;

    Dsce_SeqFlightRecord(DSCE_SEQ_FLIGHT_CHANNEL_OPCODE, seqPlayer, channel, opcode, pc,
                         Dsce_SeqFlightOpcodeWord(seqPlayer, pc), state);
}

void Dsce_AudioSeqPlayerOpcodeTrace(void* playerPtr, void* pc, s32 opcode) {
    SequencePlayer* seqPlayer = playerPtr;
    u32 state = ((u32)seqPlayer->scriptState.depth << 24) |
                ((u32)(u8)seqPlayer->scriptState.value << 16) | seqPlayer->delay;

    Dsce_SeqFlightRecord(DSCE_SEQ_FLIGHT_PLAYER_OPCODE, seqPlayer, NULL, opcode, pc,
                         Dsce_SeqFlightOpcodeWord(seqPlayer, pc), state);
}

void Dsce_AudioSeqWriteTrace(void* playerPtr, void* channelPtr, void* pc, s32 opcode,
                             void* target, u32 oldValue, u32 newValue) {
    SequencePlayer* seqPlayer = playerPtr;
    u32 offset = (u8*)target - seqPlayer->seqData;

    Dsce_SeqFlightRecord(DSCE_SEQ_FLIGHT_SEQUENCE_WRITE, seqPlayer, channelPtr, opcode, pc,
                         offset, ((oldValue & 0xFFFF) << 16) | (newValue & 0xFFFF));
}

void Dsce_AudioSeqStopChanFaultTrace(void* channelPtr, void* pc, s32 requestedIndex) {
    SequenceChannel* channel = channelPtr;
    SequencePlayer* seqPlayer = channel->seqPlayer;
    u32 target = (requestedIndex == SEQ_NUM_CHANNELS) ? (u32)seqPlayer->scriptState.pc : 0;

    Dsce_SeqFlightRecord(DSCE_SEQ_FLIGHT_BAD_STOPCHAN, seqPlayer, channel, 0xCD,
                         pc, requestedIndex, target);
    gDsceSeqFlightFrozen = 1;
}

void Dsce_AudioSeqLoadTrace(void* playerPtr, void* seqData, s32 seqId, u32 size) {
    SequencePlayer* seqPlayer = playerPtr;

    Dsce_SeqFlightRecord(DSCE_SEQ_FLIGHT_SEQUENCE_LOAD, seqPlayer, NULL, seqId, seqData, seqId, size);
}

/* Called by the debug-only instrumentation in osAiSetNextBuffer. The audio thread
 * writes one compact snapshot; the game-thread poller copies it into the ring. */
void Dsce_AiSubmitTrace(void* buffer, u32 size, s32 result, u32 status) {
    gDsceAiSubmitTrace.attempts++;
    if (result == 0) {
        gDsceAiSubmitTrace.successes++;
    } else {
        gDsceAiSubmitTrace.failures++;
    }
    gDsceAiSubmitTrace.lastResult = result;
    gDsceAiSubmitTrace.lastBuffer = (u32)buffer;
    gDsceAiSubmitTrace.lastSize = size;
    gDsceAiSubmitTrace.lastStatus = status;
    gDsceAiSubmitTrace.lastLength = IO_READ(AI_LEN_REG);
}

/* Called from the debug-only audio-manager patch. event: 1 timeout, 0 task
 * completed, -1 the retail retry budget was exhausted and recovery continued. */
void Dsce_AudioMgrTimeoutTrace(s32 event) {
    if (event > 0) {
        gDsceAudioMgrTrace.timeouts++;
        gDsceAudioMgrTrace.consecutive++;
        if (gDsceAudioMgrTrace.consecutive > gDsceAudioMgrTrace.maxConsecutive) {
            gDsceAudioMgrTrace.maxConsecutive = gDsceAudioMgrTrace.consecutive;
        }
    } else if (event < 0) {
        gDsceAudioMgrTrace.exhaustedBursts++;
    } else {
        gDsceAudioMgrTrace.successes++;
        gDsceAudioMgrTrace.consecutive = 0;
    }
}

void Dsce_AudioUpdatePhaseTrace(s32 phase, s32 a, s32 b) {
    gDsceAudioUpdateTrace.phase = phase;
    gDsceAudioUpdateTrace.a = a;
    gDsceAudioUpdateTrace.b = b;
    gDsceAudioUpdateTrace.taskCount = gAudioCtx.totalTaskCount;
}

void Dsce_AudioDmaSubmitTrace(uintptr_t devAddr, void* ramAddr, size_t size, OSMesgQueue* queue) {
    s32 i;

    gDsceAudioUpdateTrace.dmaSubmits++;
    gDsceAudioUpdateTrace.lastDmaDevAddr = devAddr;
    gDsceAudioUpdateTrace.lastDmaSize = size;
    gDsceAudioUpdateTrace.lastDmaQueue = (u32)queue;
    for (i = 0; i < ARRAY_COUNT(gAudioCtx.seqPlayers); i++) {
        SequencePlayer* seqPlayer = &gAudioCtx.seqPlayers[i];
        u32 seqSize = Dsce_SeqFlightSequenceSize(seqPlayer);
        u32 dmaStart = (u32)ramAddr;
        u32 dmaEnd = dmaStart + size;
        u32 seqStart = (u32)seqPlayer->seqData;
        u32 seqEnd = seqStart + seqSize;

        if (seqPlayer->enabled && (seqSize != 0) && (dmaStart < seqEnd) && (dmaEnd > seqStart)) {
            Dsce_SeqFlightRecord(DSCE_SEQ_FLIGHT_DMA_OVERLAP, seqPlayer, NULL, 0, ramAddr,
                                 devAddr, size);
        }
    }
}

void Dsce_AudioSeqLayerTrace(void* channel, s32 layerIndex, void* layer, s32 fontId) {
    gDsceAudioSeqTrace.channel = (u32)channel;
    gDsceAudioSeqTrace.layer = (u32)layer;
    gDsceAudioSeqTrace.layerIndex = layerIndex;
    gDsceAudioSeqTrace.fontId = fontId;
}

void Dsce_AudioSeqInvalidTrace(void* channel, s32 layerIndex, void* layer, s32 fontId) {
    SequenceChannel* seqChannel = channel;
    s32 playerIndex;
    s32 channelIndex;

    if (gDsceAudioSeqTrace.invalidCount != 0) {
        gDsceAudioSeqTrace.invalidCount++;
        return;
    }
    gDsceAudioSeqTrace.invalidCount = 1;
    gDsceAudioSeqTrace.invalidChannelPtr = (u32)channel;
    gDsceAudioSeqTrace.invalidLayer = (u32)layer;
    gDsceAudioSeqTrace.invalidLayerIndex = layerIndex;
    gDsceAudioSeqTrace.invalidFontId = fontId;
    gDsceAudioSeqTrace.invalidPlayer = -1;
    gDsceAudioSeqTrace.invalidChannel = -1;
    gDsceAudioSeqTrace.invalidTask = gAudioCtx.totalTaskCount;
    if (((u32)channel < (u32)gAudioCtx.miscPool.startAddr) ||
        ((u32)channel + sizeof(SequenceChannel) > (u32)gAudioCtx.miscPool.curAddr)) {
        gDsceAudioSeqTrace.invalidScriptPc = 0;
        gDsceAudioSeqTrace.invalidSeqData = 0;
        return;
    }
    gDsceAudioSeqTrace.invalidScriptPc = (u32)seqChannel->scriptState.pc;
    gDsceAudioSeqTrace.invalidDepth = seqChannel->scriptState.depth;
    gDsceAudioSeqTrace.invalidValue = seqChannel->scriptState.value;
    gDsceAudioSeqTrace.invalidUnk22 = seqChannel->unk_22;
    gDsceAudioSeqTrace.invalidDynTable = (u32)seqChannel->dynTable;
    gDsceAudioSeqTrace.invalidStack[0] = (u32)seqChannel->scriptState.stack[0];
    gDsceAudioSeqTrace.invalidStack[1] = (u32)seqChannel->scriptState.stack[1];
    gDsceAudioSeqTrace.invalidStack[2] = (u32)seqChannel->scriptState.stack[2];
    gDsceAudioSeqTrace.invalidStack[3] = (u32)seqChannel->scriptState.stack[3];
    gDsceAudioSeqTrace.invalidLayers[0] = (u32)seqChannel->layers[0];
    gDsceAudioSeqTrace.invalidLayers[1] = (u32)seqChannel->layers[1];
    gDsceAudioSeqTrace.invalidLayers[2] = (u32)seqChannel->layers[2];
    gDsceAudioSeqTrace.invalidLayers[3] = (u32)seqChannel->layers[3];
    gDsceAudioSeqTrace.invalidSeqData = (u32)seqChannel->seqPlayer->seqData;
    Dsce_SeqFlightRecord(DSCE_SEQ_FLIGHT_BAD_POINTER, seqChannel->seqPlayer, seqChannel, 0,
                         seqChannel->scriptState.pc, layerIndex, (s32)layer);
    gDsceSeqFlightFrozen = 1;
    for (playerIndex = 0; playerIndex < ARRAY_COUNT(gAudioCtx.seqPlayers); playerIndex++) {
        for (channelIndex = 0; channelIndex < ARRAY_COUNT(gAudioCtx.seqPlayers[playerIndex].channels);
             channelIndex++) {
            if (gAudioCtx.seqPlayers[playerIndex].channels[channelIndex] == channel) {
                gDsceAudioSeqTrace.invalidPlayer = playerIndex;
                gDsceAudioSeqTrace.invalidChannel = channelIndex;
                return;
            }
        }
    }
}

void Dsce_AudioSeqChannelPtrTrace(void* player, s32 slot, void* badPtr) {
    SequencePlayer* seqPlayer = player;
    s32 i;

    if (seqPlayer == NULL) {
        u32 badAddress = (u32)badPtr;
        u32 bestOffset = 0xFFFFFFFF;

        for (i = 0; i < ARRAY_COUNT(gAudioCtx.seqPlayers); i++) {
            if ((u32)gAudioCtx.seqPlayers[i].scriptState.pc == badAddress) {
                seqPlayer = &gAudioCtx.seqPlayers[i];
                break;
            }
        }
        for (i = 0; i < ARRAY_COUNT(gAudioCtx.seqPlayers); i++) {
            u32 seqAddress = (u32)gAudioCtx.seqPlayers[i].seqData;
            u32 offset = badAddress - seqAddress;

            if ((seqPlayer == NULL) && (badAddress >= seqAddress) &&
                (offset < bestOffset) && (offset < 0x100000)) {
                seqPlayer = &gAudioCtx.seqPlayers[i];
                bestOffset = offset;
            }
        }
    }

    if (gDsceAudioChannelPtrTrace.count != 0) {
        gDsceAudioChannelPtrTrace.count++;
        return;
    }
    Dsce_SeqFlightRecord(DSCE_SEQ_FLIGHT_BAD_POINTER, seqPlayer, NULL, 0, badPtr, slot, (s32)badPtr);
    gDsceSeqFlightFrozen = 1;
    gDsceAudioChannelPtrTrace.count = 1;
    gDsceAudioChannelPtrTrace.player = (seqPlayer != NULL) ? seqPlayer->playerIndex : -1;
    gDsceAudioChannelPtrTrace.slot = slot;
    gDsceAudioChannelPtrTrace.badPtr = (u32)badPtr;
    gDsceAudioChannelPtrTrace.task = gAudioCtx.totalTaskCount;
    gDsceAudioChannelPtrTrace.seqData = (seqPlayer != NULL) ? (u32)seqPlayer->seqData : 0;
    gDsceAudioChannelPtrTrace.miscStart = (u32)gAudioCtx.miscPool.startAddr;
    gDsceAudioChannelPtrTrace.miscCur = (u32)gAudioCtx.miscPool.curAddr;
    if (seqPlayer != NULL) {
        for (i = 0; i < ARRAY_COUNT(seqPlayer->channels); i++) {
            gDsceAudioChannelPtrTrace.channels[i] = (u32)seqPlayer->channels[i];
        }
        gDsceAudioChannelPtrTrace.scriptPc = (u32)seqPlayer->scriptState.pc;
        gDsceAudioChannelPtrTrace.depth = seqPlayer->scriptState.depth;
        gDsceAudioChannelPtrTrace.value = seqPlayer->scriptState.value;
        gDsceAudioChannelPtrTrace.seqId = seqPlayer->seqId;
        for (i = 0; i < ARRAY_COUNT(seqPlayer->scriptState.stack); i++) {
            gDsceAudioChannelPtrTrace.stack[i] = (u32)seqPlayer->scriptState.stack[i];
        }
    }
}

void Dsce_AudioSeqInvalidChannelTrace(void* channel, void* sourceRa) {
    s32 i;

    if (gDsceAudioChannelPtrTrace.count != 0) {
        Dsce_AudioSeqChannelPtrTrace(NULL, -1, channel);
        return;
    }
    gDsceAudioChannelPtrTrace.sourceRa = (u32)sourceRa;
    gDsceAudioChannelPtrTrace.matchingLayer = -1;
    for (i = 0; i < ARRAY_COUNT(gAudioCtx.sequenceLayers); i++) {
        SequenceLayer* layer = &gAudioCtx.sequenceLayers[i];

        if (layer->channel == channel) {
            gDsceAudioChannelPtrTrace.matchingLayer = i;
            gDsceAudioChannelPtrTrace.matchingLayerPc = (u32)layer->scriptState.pc;
            gDsceAudioChannelPtrTrace.matchingLayerNote = (u32)layer->note;
            break;
        }
    }
    Dsce_AudioSeqChannelPtrTrace(NULL, -1, channel);
}

void Dsce_AudioSlowLoadContextTrace(void* channel, void* pc, s32 port) {
    SequenceChannel* seqChannel = channel;
    u8* opcode = pc;
    s32 playerIndex;
    s32 channelIndex;

    gDsceAudioSlowLoadTrace.contextChannel = (u32)channel;
    gDsceAudioSlowLoadTrace.contextPc = (u32)pc;
    gDsceAudioSlowLoadTrace.contextPlayer = -1;
    gDsceAudioSlowLoadTrace.contextChannelIndex = -1;
    gDsceAudioSlowLoadTrace.contextPort = port;
    gDsceAudioSlowLoadTrace.contextSeqData = 0;
    gDsceAudioSlowLoadTrace.contextOpcodeWord = ((u32)opcode[0] << 24) | ((u32)opcode[1] << 16) |
                                                 ((u32)opcode[2] << 8) | opcode[3];
    gDsceAudioSlowLoadTrace.contextScriptPc = (u32)seqChannel->scriptState.pc;
    gDsceAudioSlowLoadTrace.contextValue = seqChannel->scriptState.value;
    gDsceAudioSlowLoadTrace.contextDepth = seqChannel->scriptState.depth;
    gDsceAudioSlowLoadTrace.contextUnk22 = seqChannel->unk_22;
    gDsceAudioSlowLoadTrace.contextDynTable = (u32)seqChannel->dynTable;
    gDsceAudioSlowLoadTrace.contextLayers[0] = (u32)seqChannel->layers[0];
    gDsceAudioSlowLoadTrace.contextLayers[1] = (u32)seqChannel->layers[1];
    gDsceAudioSlowLoadTrace.contextLayers[2] = (u32)seqChannel->layers[2];
    gDsceAudioSlowLoadTrace.contextLayers[3] = (u32)seqChannel->layers[3];
    for (playerIndex = 0; playerIndex < ARRAY_COUNT(gAudioCtx.seqPlayers); playerIndex++) {
        for (channelIndex = 0; channelIndex < ARRAY_COUNT(gAudioCtx.seqPlayers[playerIndex].channels);
             channelIndex++) {
            if (gAudioCtx.seqPlayers[playerIndex].channels[channelIndex] == channel) {
                gDsceAudioSlowLoadTrace.contextPlayer = playerIndex;
                gDsceAudioSlowLoadTrace.contextChannelIndex = channelIndex;
                gDsceAudioSlowLoadTrace.contextSeqData = (u32)gAudioCtx.seqPlayers[playerIndex].seqData;
                return;
            }
        }
    }
}

void Dsce_AudioSlowLoadTrace(s32 fontId, s32 instId, void* sample, void* isDone, s32 invalid) {
    gDsceAudioSlowLoadTrace.calls++;
    gDsceAudioSlowLoadTrace.fontId = fontId;
    gDsceAudioSlowLoadTrace.instId = instId;
    gDsceAudioSlowLoadTrace.sample = (u32)sample;
    gDsceAudioSlowLoadTrace.isDone = (u32)isDone;
    if (invalid) {
        if (gDsceAudioSlowLoadTrace.invalidCount == 0) {
            SequencePlayer* seqPlayer = NULL;
            SequenceChannel* seqChannel = NULL;

            gDsceAudioSlowLoadTrace.invalidFontId = fontId;
            gDsceAudioSlowLoadTrace.invalidInstId = instId;
            gDsceAudioSlowLoadTrace.invalidSample = (u32)sample;
            gDsceAudioSlowLoadTrace.invalidIsDone = (u32)isDone;
            gDsceAudioSlowLoadTrace.invalidContextChannel = gDsceAudioSlowLoadTrace.contextChannel;
            gDsceAudioSlowLoadTrace.invalidContextPc = gDsceAudioSlowLoadTrace.contextPc;
            gDsceAudioSlowLoadTrace.invalidContextPlayer = gDsceAudioSlowLoadTrace.contextPlayer;
            gDsceAudioSlowLoadTrace.invalidContextChannelIndex = gDsceAudioSlowLoadTrace.contextChannelIndex;
            gDsceAudioSlowLoadTrace.invalidContextPort = gDsceAudioSlowLoadTrace.contextPort;
            gDsceAudioSlowLoadTrace.invalidContextSeqData = gDsceAudioSlowLoadTrace.contextSeqData;
            gDsceAudioSlowLoadTrace.invalidContextOpcodeWord = gDsceAudioSlowLoadTrace.contextOpcodeWord;
            gDsceAudioSlowLoadTrace.invalidContextScriptPc = gDsceAudioSlowLoadTrace.contextScriptPc;
            gDsceAudioSlowLoadTrace.invalidContextValue = gDsceAudioSlowLoadTrace.contextValue;
            gDsceAudioSlowLoadTrace.invalidContextDepth = gDsceAudioSlowLoadTrace.contextDepth;
            gDsceAudioSlowLoadTrace.invalidContextUnk22 = gDsceAudioSlowLoadTrace.contextUnk22;
            gDsceAudioSlowLoadTrace.invalidContextDynTable = gDsceAudioSlowLoadTrace.contextDynTable;
            gDsceAudioSlowLoadTrace.invalidContextLayers[0] = gDsceAudioSlowLoadTrace.contextLayers[0];
            gDsceAudioSlowLoadTrace.invalidContextLayers[1] = gDsceAudioSlowLoadTrace.contextLayers[1];
            gDsceAudioSlowLoadTrace.invalidContextLayers[2] = gDsceAudioSlowLoadTrace.contextLayers[2];
            gDsceAudioSlowLoadTrace.invalidContextLayers[3] = gDsceAudioSlowLoadTrace.contextLayers[3];
            if ((gDsceAudioSlowLoadTrace.contextPlayer >= 0) &&
                (gDsceAudioSlowLoadTrace.contextPlayer < ARRAY_COUNT(gAudioCtx.seqPlayers))) {
                seqPlayer = &gAudioCtx.seqPlayers[gDsceAudioSlowLoadTrace.contextPlayer];
            }
            if ((seqPlayer != NULL) && (gDsceAudioSlowLoadTrace.contextChannelIndex >= 0) &&
                (gDsceAudioSlowLoadTrace.contextChannelIndex < SEQ_NUM_CHANNELS)) {
                seqChannel = seqPlayer->channels[gDsceAudioSlowLoadTrace.contextChannelIndex];
            }
            Dsce_SeqFlightRecord(DSCE_SEQ_FLIGHT_BAD_SLOWLOAD, seqPlayer, seqChannel,
                                 gDsceAudioSlowLoadTrace.contextOpcodeWord >> 24,
                                 (void*)gDsceAudioSlowLoadTrace.contextPc, fontId, instId);
            gDsceSeqFlightFrozen = 1;
        }
        gDsceAudioSlowLoadTrace.invalidCount++;
    }
}
#endif /* DSCE_DBG_AUDIO */

void Dsce_Fh(u8 domain, u16 tag, s32 a, s32 b, s32 c, s32 d) {
    DsceFhRec* r = &gDsceFhRing[gDsceFhHead & (DSCE_FH_RING - 1)];

    r->seq = gDsceFhHead;
    r->domain = domain;
    r->flags = 0;
    r->tag = tag;
    r->tick = gDsceTelemetry.frame;
    r->frame = gDscePlayFrame;
    r->a = a;
    r->b = b;
    r->c = c;
    r->d = d;
    gDsceFhHead++; /* overwrites oldest; the plugin counts gaps as explicit drops */
}

#if DSCE_DBG_AUDIO
/* per-frame pollers -- called from the hook (game thread; audio-struct reads are
 * racy-by-design diagnostics, never control flow) */
typedef struct {
    u16 sfxId;
    u8 token;
    s8* reverbAdd;
    Vec3f* pos;
    f32* freqScale;
    f32* volume;
} DsceSfxRequest; /* mirrors sfx.c's file-local SfxRequest (size 0x14) */
extern DsceSfxRequest sSfxRequests[0x100];
extern u8 sSfxRequestWriteIndex;

static void Dsce_FhPollAudio(void) {
    static u8 sFhSfxRead = 0;
    static u8 sFhInit = 0;
    u8 w = sSfxRequestWriteIndex;
    u32 packedFonts;
    s32 i;

    if (!sFhInit) { /* skip the boot backlog */
        sFhSfxRead = w;
        sFhInit = 1;
    }
    while (sFhSfxRead != w) {
        DsceSfxRequest* q = &sSfxRequests[sFhSfxRead];
        Dsce_Fh(1, 0, q->sfxId, (s32)q->pos, q->token, 0);
        sFhSfxRead++;
    }
    { /* seq player 0 (ALL game sfx) health + the font latched on each SFX channel:
       * player bank ch 0-2 (nibbles 0-2), voice bank ch 13-15 (nibbles 3-5) */
        SequencePlayer* sp = &gAudioCtx.seqPlayers[SEQ_PLAYER_SFX];
        u32 fontsLo = 0; /* full font bytes: ch0|ch1<<8|ch2<<16 (player bank) */
        u32 fontsHi = 0; /* ch13|ch14<<8|ch15<<16 (voice bank) */
        u32 chanBits = 0;

        for (i = 0; i < 3; i++) {
            if (sp->channels[i] != NULL) {
                fontsLo |= (u32)sp->channels[i]->fontId << (i * 8);
                chanBits |= (sp->channels[i]->enabled ? 1u : 0u) << i;
            }
            if (sp->channels[13 + i] != NULL) {
                fontsHi |= (u32)sp->channels[13 + i]->fontId << (i * 8);
                chanBits |= (sp->channels[13 + i]->enabled ? 1u : 0u) << (3 + i);
            }
        }
        { /* note pool: the DIRECT audio-death observable. activeNotes -> 0 forever
           * while requests continue = the synth stopped; a live note with fontId 41
           * pins the poisoned-font mechanism by itself. */
            s32 activeNotes = 0;
            s32 notes41 = 0;
            s32 n;

            for (n = 0; n < gAudioCtx.numNotes; n++) {
                Note* note = &gAudioCtx.notes[n];
                if (note->sampleState.bitField0.enabled) {
                    activeNotes++;
                    if (note->playbackState.fontId == 41) {
                        notes41++;
                    }
                }
            }
            packedFonts = chanBits | ((u32)activeNotes << 8) | ((u32)notes41 << 16);
        }
        Dsce_Fh(2, 0, (sp->enabled << 1) | sp->finished, (s32)fontsLo, (s32)fontsHi,
                (s32)packedFonts);
    }
    { /* pool fill levels: used = curRamAddr - startRamAddr */
        AudioAllocPool* pp = &gAudioCtx.permanentPool;
        AudioAllocPool* cp = &gAudioCtx.cachePool;
        Dsce_Fh(3, 0, (s32)(pp->curAddr - pp->startAddr), (s32)pp->size,
                (s32)(cp->curAddr - cp->startAddr), (s32)cp->size);
    }
    { /* End-to-end ROM audio pipeline. This is sampled through uncached KSEG1 so the
       * PCM observation sees what the RSP/AI sees rather than a stale CPU cache line.
       * No value here affects gameplay or audio control flow. */
        extern AudioMgr sAudioMgr;
        u32 aiStatus = IO_READ(AI_STATUS_REG);
        u32 aiLen = IO_READ(AI_LEN_REG);
        u32 aiAddr = IO_READ(AI_DRAM_ADDR_REG) & 0x00FFFFF8;
        u32 packedIndex = ((u32)gAudioCtx.curAiBufferIndex & 3) |
                          (((u32)gAudioCtx.rspTaskIndex & 3) << 2) |
                          (((u32)sAudioMgr.cmdQueue.validCount & 0xFF) << 8) |
                          (((u32)sAudioMgr.interruptQueue.validCount & 0xFF) << 16);
        u32 packedLengths = ((u32)gAudioCtx.numSamplesPerFrame[0] & 0x3FF) |
                            (((u32)gAudioCtx.numSamplesPerFrame[1] & 0x3FF) << 10) |
                            (((u32)gAudioCtx.numSamplesPerFrame[2] & 0x3FF) << 20);
        u32 packedReset = (u32)gAudioCtx.resetStatus | ((gAudioCtx.resetTimer & 0xFF) << 8) |
                          (((u32)gAudioCtx.curAudioFrameDmaCount & 0xFF) << 16);
        s32 peak = 0;
        s32 absSum = 0;
        s32 nonzero = 0;

        /* AI addresses are 8-byte aligned physical RDRAM addresses. Sample at most 64
         * stereo words across the live DMA span; this proves whether the ROM handed AI
         * actual PCM or an all-zero buffer without copying or invalidating anything. */
        if ((aiLen >= sizeof(s16)) && (aiAddr < 0x800000)) {
            volatile s16* pcm = (volatile s16*)PHYS_TO_K1(aiAddr);
            u32 words = aiLen / sizeof(s16);
            u32 samples = (words < 64) ? words : 64;
            u32 step = (words / samples) ? (words / samples) : 1;
            u32 n;

            for (n = 0; n < samples; n++) {
                s32 v = pcm[n * step];
                s32 mag = (v < 0) ? -v : v;
                if (mag > peak) {
                    peak = mag;
                }
                absSum += mag;
                nonzero += (v != 0);
            }
        }

        Dsce_Fh(4, 0, gAudioCtx.totalTaskCount, packedIndex, aiLen, aiStatus);
        Dsce_Fh(4, 1, (s32)packedLengths,
                (gAudioCtx.curTask != NULL) ? (s32)gAudioCtx.curTask->task.t.data_size : -1,
                (s32)packedReset, (s32)gAudioCtx.audioErrorFlags);
        Dsce_Fh(4, 2, aiAddr, peak, absSum, nonzero);
        Dsce_Fh(4, 3, (s32)sAudioMgr.rspTask, (s32)gScheduler.curRSPTask,
                (s32)sAudioMgr.audioTask.state, (s32)sAudioMgr.audioTask.flags);
        Dsce_Fh(4, 4, gDsceAiSubmitTrace.attempts, gDsceAiSubmitTrace.failures,
                gDsceAiSubmitTrace.successes, gDsceAiSubmitTrace.lastResult);
        Dsce_Fh(4, 5, gDsceAiSubmitTrace.lastBuffer, gDsceAiSubmitTrace.lastSize,
                gDsceAiSubmitTrace.lastStatus, gDsceAiSubmitTrace.lastLength);
        Dsce_Fh(4, 6, gDsceAudioMgrTrace.timeouts, gDsceAudioMgrTrace.successes,
                gDsceAudioMgrTrace.exhaustedBursts,
                (gDsceAudioMgrTrace.maxConsecutive << 16) |
                    (gDsceAudioMgrTrace.consecutive & 0xFFFF));
        Dsce_Fh(4, 7, gDsceAudioUpdateTrace.phase, gDsceAudioUpdateTrace.a,
                gDsceAudioUpdateTrace.b, gDsceAudioUpdateTrace.taskCount);
        Dsce_Fh(4, 8, gDsceAudioUpdateTrace.dmaSubmits,
                gDsceAudioUpdateTrace.lastDmaDevAddr, gDsceAudioUpdateTrace.lastDmaSize,
                gDsceAudioUpdateTrace.lastDmaQueue);
        Dsce_Fh(4, 13, (s32)sAudioMgr.thread.context.pc, (s32)sAudioMgr.thread.context.sp,
                (s32)sAudioMgr.thread.context.ra,
                ((s32)sAudioMgr.thread.state << 16) | (sAudioMgr.thread.id & 0xFFFF));
        Dsce_Fh(4, 14, (s32)sAudioMgr.thread.context.a0, (s32)sAudioMgr.thread.context.badvaddr,
                (s32)sAudioMgr.thread.context.cause,
                ((s32)sAudioMgr.thread.flags << 16) | sAudioMgr.thread.state);
        Dsce_Fh(4, 15, gDsceAudioSeqTrace.channel, gDsceAudioSeqTrace.layer,
                gDsceAudioSeqTrace.layerIndex, gDsceAudioSeqTrace.fontId);
        Dsce_Fh(4, 16, gDsceAudioSeqTrace.invalidCount, gDsceAudioSeqTrace.invalidLayer,
                gDsceAudioSeqTrace.invalidLayerIndex, gDsceAudioSeqTrace.invalidFontId);
        Dsce_Fh(4, 17, gDsceAudioSeqTrace.invalidChannelPtr, gDsceAudioSeqTrace.invalidPlayer,
                gDsceAudioSeqTrace.invalidChannel, gDsceAudioSeqTrace.invalidTask);
        Dsce_Fh(4, 18, gDsceAudioSlowLoadTrace.calls, gDsceAudioSlowLoadTrace.fontId,
                gDsceAudioSlowLoadTrace.instId, gDsceAudioSlowLoadTrace.sample);
        Dsce_Fh(4, 19, gDsceAudioSlowLoadTrace.invalidCount, gDsceAudioSlowLoadTrace.invalidFontId,
                gDsceAudioSlowLoadTrace.invalidInstId, gDsceAudioSlowLoadTrace.invalidSample);
        Dsce_Fh(4, 20, gDsceAudioSlowLoadTrace.invalidContextChannel,
                gDsceAudioSlowLoadTrace.invalidContextPc,
                ((gDsceAudioSlowLoadTrace.invalidContextPlayer & 0xFF) << 24) |
                    ((gDsceAudioSlowLoadTrace.invalidContextChannelIndex & 0xFF) << 16) |
                    (gDsceAudioSlowLoadTrace.invalidContextPort & 0xFFFF),
                gDsceAudioSlowLoadTrace.invalidIsDone);
        Dsce_Fh(4, 21, gDsceAudioSlowLoadTrace.invalidContextSeqData,
                gDsceAudioSlowLoadTrace.invalidContextPc - gDsceAudioSlowLoadTrace.invalidContextSeqData,
                gDsceAudioSlowLoadTrace.invalidContextPort, gDsceAudioUpdateTrace.taskCount);
        Dsce_Fh(4, 22, (s32)gGraphThread.context.pc, (s32)gGraphThread.context.sp,
                (s32)gGraphThread.context.ra,
                ((s32)gGraphThread.state << 16) | (gGraphThread.id & 0xFFFF));
        Dsce_Fh(4, 23, (s32)gGraphThread.context.a0, (s32)gGraphThread.context.badvaddr,
                (s32)gGraphThread.context.cause,
                ((s32)gGraphThread.flags << 16) | gGraphThread.state);
        Dsce_Fh(4, 24, gDsceAudioSlowLoadTrace.invalidContextOpcodeWord,
                gDsceAudioSlowLoadTrace.invalidContextScriptPc,
                gDsceAudioSlowLoadTrace.invalidContextValue,
                gDsceAudioSlowLoadTrace.invalidContextDepth);
        Dsce_Fh(4, 25, gDsceAudioSlowLoadTrace.invalidContextUnk22,
                gDsceAudioSlowLoadTrace.invalidContextDynTable,
                gDsceAudioSlowLoadTrace.invalidContextLayers[0],
                gDsceAudioSlowLoadTrace.invalidContextLayers[1]);
        Dsce_Fh(4, 26, gDsceAudioSlowLoadTrace.invalidContextLayers[2],
                gDsceAudioSlowLoadTrace.invalidContextLayers[3],
                gDsceAudioSlowLoadTrace.invalidContextPc,
                gDsceAudioSlowLoadTrace.invalidContextSeqData);
        Dsce_Fh(4, 27, gDsceAudioSeqTrace.invalidScriptPc,
                gDsceAudioSeqTrace.invalidScriptPc - gDsceAudioSeqTrace.invalidSeqData,
                ((gDsceAudioSeqTrace.invalidDepth & 0xFFFF) << 16) |
                    (gDsceAudioSeqTrace.invalidValue & 0xFFFF),
                gDsceAudioSeqTrace.invalidUnk22);
        Dsce_Fh(4, 28, gDsceAudioSeqTrace.invalidDynTable,
                gDsceAudioSeqTrace.invalidStack[0], gDsceAudioSeqTrace.invalidStack[1],
                gDsceAudioSeqTrace.invalidStack[2]);
        Dsce_Fh(4, 29, gDsceAudioSeqTrace.invalidStack[3],
                gDsceAudioSeqTrace.invalidLayers[0], gDsceAudioSeqTrace.invalidLayers[1],
                gDsceAudioSeqTrace.invalidLayers[2]);
        Dsce_Fh(4, 30, gDsceAudioSeqTrace.invalidLayers[3],
                gDsceAudioSeqTrace.invalidSeqData, gDsceAudioSeqTrace.invalidChannelPtr,
                gDsceAudioSeqTrace.invalidTask);
        Dsce_Fh(4, 31, gDsceAudioChannelPtrTrace.count, gDsceAudioChannelPtrTrace.player,
                gDsceAudioChannelPtrTrace.slot, gDsceAudioChannelPtrTrace.badPtr);
        Dsce_Fh(4, 32, gDsceAudioChannelPtrTrace.task, gDsceAudioChannelPtrTrace.seqData,
                gDsceAudioChannelPtrTrace.miscStart, gDsceAudioChannelPtrTrace.miscCur);
        Dsce_Fh(4, 33, gDsceAudioChannelPtrTrace.channels[0], gDsceAudioChannelPtrTrace.channels[1],
                gDsceAudioChannelPtrTrace.channels[2], gDsceAudioChannelPtrTrace.channels[3]);
        Dsce_Fh(4, 34, gDsceAudioChannelPtrTrace.channels[4], gDsceAudioChannelPtrTrace.channels[5],
                gDsceAudioChannelPtrTrace.channels[6], gDsceAudioChannelPtrTrace.channels[7]);
        Dsce_Fh(4, 35, gDsceAudioChannelPtrTrace.channels[8], gDsceAudioChannelPtrTrace.channels[9],
                gDsceAudioChannelPtrTrace.channels[10], gDsceAudioChannelPtrTrace.channels[11]);
        Dsce_Fh(4, 36, gDsceAudioChannelPtrTrace.channels[12], gDsceAudioChannelPtrTrace.channels[13],
                gDsceAudioChannelPtrTrace.channels[14], gDsceAudioChannelPtrTrace.channels[15]);
        Dsce_Fh(4, 37, gDsceAudioChannelPtrTrace.scriptPc,
                gDsceAudioChannelPtrTrace.scriptPc - gDsceAudioChannelPtrTrace.seqData,
                ((gDsceAudioChannelPtrTrace.depth & 0xFFFF) << 16) |
                    (gDsceAudioChannelPtrTrace.value & 0xFFFF),
                gDsceAudioChannelPtrTrace.seqId);
        Dsce_Fh(4, 38, gDsceAudioChannelPtrTrace.stack[0], gDsceAudioChannelPtrTrace.stack[1],
                gDsceAudioChannelPtrTrace.stack[2], gDsceAudioChannelPtrTrace.stack[3]);
        Dsce_Fh(4, 39, gDsceAudioChannelPtrTrace.sourceRa,
                gDsceAudioChannelPtrTrace.matchingLayer,
                gDsceAudioChannelPtrTrace.matchingLayerPc,
                gDsceAudioChannelPtrTrace.matchingLayerNote);
    }
}
#endif /* DSCE_DBG_AUDIO */
#endif /* DSCE_DBG_FIREHOSE */
/* =============== end DSCE FIREHOSE =============== */


#if DSCE_XTEST
/* [DSCE XTEST R3] the kernel's play_sound logs each request against the SANDBOX tick
 * (gDsceTelemetry.frame mid-tick = the about-to-complete tick), aligning the sound
 * stream to the same tick axis the kinematic telemetry uses. */
u32 Dsce_XtestTick(void) {
    return gDsceTelemetry.frame;
}
#endif
/* [DSCE LOG] arms the DmaMgr request/error logging (z_std_dma.c) from the moment the Brother's
 * Mask transform begins (playerForm=MARIO is set at func_808388B8 time, before the freeze window) */
s32 gDsceDmaLogArmed = 0;
/* Song-of-Healing grace window: DEFINED IN THE OVERLAY (z_dsce_mario.c) like gDsceDebugSong --
 * that's the overlay<->code binding direction proven to work for cross-segment writes. */
extern int gDsceSongHealLatch;
s32 gDsceScreamDelayFrames = 0; /* mask-on scream lead-in, armed at the transform-voice cue */

/* Flash writes erase a whole 0x80-page sector and SysFlashrom_ExecWrite deliberately
 * crashes if the starting page is not sector-aligned.  Keep every DSCE write behind a
 * compile-time alignment guard.  The marker shares the otherwise-unused last page of
 * the options-backup sector, so that whole sector must be read/preserved/re-written. */
#define DSCE_FLASH_SECTOR_PAGES 0x80
#define DSCE_FLASH_PAGE_BYTES 0x80
#define DSCE_FILE1_SECTOR_PAGE 0x000
#define DSCE_OPTIONS_MAIN_PAGE 0x300
#define DSCE_SEED_MARKER_SECTOR_PAGE 0x380
#define DSCE_SEED_MARKER_PAGE 0x3FF
#define DSCE_SEED_MARKER_OFFSET ((DSCE_SEED_MARKER_PAGE - DSCE_SEED_MARKER_SECTOR_PAGE) * DSCE_FLASH_PAGE_BYTES)
#define DSCE_FLASH_WRITE_SYNC_ALIGNED(buf, page, pageCount)                                      \
    do {                                                                                         \
        typedef char DsceFlashWriteStartMustBeSectorAligned[                                     \
            (((page) & (DSCE_FLASH_SECTOR_PAGES - 1)) == 0) ? 1 : -1];                           \
        (void)sizeof(DsceFlashWriteStartMustBeSectorAligned);                                    \
        SysFlashrom_WriteSync((buf), (page), (pageCount));                                       \
    } while (0)
static const u8 sDsceSeedMarker[16] = {
    'D', 'S', 'C', 'E', 'S', 'E', 'E', 'D', '0', '0', '0', '1', 0xA5, 0x1D, 0x5A, 0xE1
};

static s32 Dsce_FlashHasSeedMarker(SramContext* sramCtx) {
    s32 i;

    bzero(sramCtx->saveBuf, SAVE_BUFFER_SIZE);
    /* A read failure is not permission to write. */
    if (SysFlashrom_Read(sramCtx->saveBuf, DSCE_SEED_MARKER_PAGE, 1) != 0) {
        return true;
    }
    for (i = 0; i < ARRAY_COUNT(sDsceSeedMarker); i++) {
        if (sramCtx->saveBuf[i] != sDsceSeedMarker[i]) {
            return false;
        }
    }
    return true;
}

static void Dsce_WriteSeedMarker(SramContext* sramCtx) {
    bzero(sramCtx->saveBuf, SAVE_BUFFER_SIZE);
    /* Preserve the options backup at the start of this sector.  A direct write at
     * 0x3FF is illegal and enters MM's Fault_AddHungupAndCrash path. */
    if (SysFlashrom_Read(sramCtx->saveBuf, DSCE_SEED_MARKER_SECTOR_PAGE, DSCE_FLASH_SECTOR_PAGES) != 0) {
        return;
    }
    Lib_MemCpy(&sramCtx->saveBuf[DSCE_SEED_MARKER_OFFSET], sDsceSeedMarker, sizeof(sDsceSeedMarker));
    DSCE_FLASH_WRITE_SYNC_ALIGNED(sramCtx->saveBuf, DSCE_SEED_MARKER_SECTOR_PAGE, DSCE_FLASH_SECTOR_PAGES);
}

/* Returns -1 on a read error, 0 only for an erased/zeroed slot, and 1 for a
 * valid OR suspicious slot.  Corruption therefore fails closed instead of being
 * mistaken for free space that the alpha seed may overwrite. */
static s32 Dsce_FlashCopyPlayerDataStatus(SramContext* sramCtx, s32 copyIndex) {
    Save* save;
    u16 storedChecksum;
    u16 calculatedChecksum;
    s32 validName;
    s32 allZero = true;
    s32 allErased = true;
    s32 i;

    bzero(sramCtx->saveBuf, SAVE_BUFFER_SIZE);
    if (SysFlashrom_Read(sramCtx->saveBuf, gFlashSaveStartPages[copyIndex],
                         gFlashSaveNumPages[copyIndex]) != 0) {
        return -1;
    }

    save = (Save*)sramCtx->saveBuf;
    validName = (save->saveInfo.playerData.newf[0] == 'Z') &&
                (save->saveInfo.playerData.newf[1] == 'E') &&
                (save->saveInfo.playerData.newf[2] == 'L') &&
                (save->saveInfo.playerData.newf[3] == 'D') &&
                (save->saveInfo.playerData.newf[4] == 'A') &&
                (save->saveInfo.playerData.newf[5] == '3');
    storedChecksum = save->saveInfo.checksum;
    save->saveInfo.checksum = 0;
    calculatedChecksum = Sram_CalcChecksum(save, sizeof(Save));
    save->saveInfo.checksum = storedChecksum;
    if (validName && (storedChecksum == calculatedChecksum)) {
        return 1;
    }
    for (i = 0; i < sizeof(Save); i++) {
        if (sramCtx->saveBuf[i] != 0) {
            allZero = false;
        }
        if (sramCtx->saveBuf[i] != 0xFF) {
            allErased = false;
        }
    }
    return (allZero || allErased) ? 0 : 1;
}

/* Seed File 1 only on unseeded FlashRAM with no player data.  New-file creation remains completely
 * vanilla; this is an optional ready-made file the player may open, copy, or delete.
 * Its state mirrors the first Song-of-Time reset after the mandatory Deku tutorial:
 * Dawn of the First Day in South Clock Town, human Link, Tatl, magic, the Ocarina,
 * Deku Mask, Song of Time, Song of Healing, and only the intro-completion flags. */
void Dsce_SeedPostTutorialSave(SramContext* sramCtx) {
    static const u8 sLinkName[8] = { 0x15, 0x2C, 0x31, 0x2E, 0x3E, 0x3E, 0x3E, 0x3E };
    static const char sValidSaveName[6] = { 'Z', 'E', 'L', 'D', 'A', '3' };
    s32 copyIndex;

    if (!gSaveContext.flashSaveAvailable) {
        return;
    }
    if (Dsce_FlashHasSeedMarker(sramCtx)) {
        return;
    }

    /* Files 1 and 2 each have a main and backup copy (indices 0..3). */
    for (copyIndex = 0; copyIndex < 4; copyIndex++) {
        s32 status = Dsce_FlashCopyPlayerDataStatus(sramCtx, copyIndex);
        if (status < 0) {
            return;
        }
        if (status > 0) {
            Dsce_WriteSeedMarker(sramCtx);
            return;
        }
    }

    Sram_InitNewSave();
    Lib_MemCpy(gSaveContext.save.saveInfo.playerData.newf, sValidSaveName, sizeof(sValidSaveName));
    Lib_MemCpy(gSaveContext.save.saveInfo.playerData.playerName, sLinkName, sizeof(sLinkName));

    gSaveContext.save.entrance = ENTRANCE(SOUTH_CLOCK_TOWN, 0);
    gSaveContext.save.cutsceneIndex = 0;
    gSaveContext.nextCutsceneIndex = 0;
    gSaveContext.save.playerForm = PLAYER_FORM_HUMAN;
    gSaveContext.save.equippedMask = PLAYER_MASK_NONE;
    gSaveContext.save.hasTatl = true;
    gSaveContext.save.isFirstCycle = true;
    gSaveContext.save.isOwlSave = false;
    gSaveContext.save.eventDayCount = 0;
    gSaveContext.save.day = 0;
    gSaveContext.save.time = CLOCK_TIME(6, 0) - 1;
    gSaveContext.save.saveInfo.playerData.threeDayResetCount = 1;
    gSaveContext.save.saveInfo.playerData.isMagicAcquired = true;
    gSaveContext.save.saveInfo.playerData.magic = MAGIC_NORMAL_METER;
    gSaveContext.save.saveInfo.playerData.magicLevel = 0;

    INV_CONTENT(ITEM_OCARINA_OF_TIME) = ITEM_OCARINA_OF_TIME;
    INV_CONTENT(ITEM_MASK_DEKU) = ITEM_MASK_DEKU;
    SET_QUEST_ITEM(QUEST_SONG_TIME);
    SET_QUEST_ITEM(QUEST_SONG_HEALING);
    SET_WEEKEVENTREG(WEEKEVENTREG_59_04);
    SET_WEEKEVENTREG(WEEKEVENTREG_31_04);
    gSaveContext.cycleSceneFlags[SCENE_INSIDETOWER].switch0 = 1;
    gSaveContext.save.saveInfo.permanentSceneFlags[SCENE_INSIDETOWER].switch0 = 1;

    gSaveContext.save.saveInfo.checksum = 0;
    gSaveContext.save.saveInfo.checksum = Sram_CalcChecksum(&gSaveContext.save, sizeof(Save));
    bzero(sramCtx->saveBuf, SAVE_BUFFER_SIZE);
    Lib_MemCpy(sramCtx->saveBuf, &gSaveContext.save, sizeof(Save));
    Lib_MemCpy(&sramCtx->saveBuf[0x2000], &gSaveContext.save, sizeof(Save));
    /* Main (page 0) and backup (page 0x40) share one physical erase sector. */
    DSCE_FLASH_WRITE_SYNC_ALIGNED(sramCtx->saveBuf, DSCE_FILE1_SECTOR_PAGE, DSCE_FLASH_SECTOR_PAGES);

    /* A fresh device also needs valid default options. */
    gSaveContext.options.optionId = 0xA51D;
    gSaveContext.options.language = LANGUAGE_ENG;
    gSaveContext.options.audioSetting = SAVE_AUDIO_STEREO;
    gSaveContext.options.languageSetting = 0;
    gSaveContext.options.zTargetSetting = 0;
    bzero(sramCtx->saveBuf, SAVE_BUFFER_SIZE);
    Lib_MemCpy(sramCtx->saveBuf, &gSaveContext.options, sizeof(SaveOptions));
    DSCE_FLASH_WRITE_SYNC_ALIGNED(sramCtx->saveBuf, DSCE_OPTIONS_MAIN_PAGE, 1);
    DSCE_FLASH_WRITE_SYNC_ALIGNED(sramCtx->saveBuf, DSCE_SEED_MARKER_SECTOR_PAGE, 1);
    Dsce_WriteSeedMarker(sramCtx);
}

/* [DSCE TESTBOOT] Boot STRAIGHT into gameplay for the headless test pipeline: synthesize a
 * debug save (Sram_InitDebugSave -- full inventory/progression) and jump to Play in South
 * Clock Town, skipping logo/title/file-select/name-entry entirely. Deterministic, menu-free,
 * build-proof. Compiled in only when make mod TESTBOOT=1 (out/mm-dsce-test.z64). */
int Dsce_TestBoot(GameState* gs) {
#if DSCE_TESTBOOT
    Sram_InitDebugSave();
    gSaveContext.fileNum = 0;
    gSaveContext.gameMode = GAMEMODE_NORMAL;
    gSaveContext.respawnFlag = 0;
#ifndef DSCE_TB_ENTRANCE
#define DSCE_TB_ENTRANCE ENTRANCE(SOUTH_CLOCK_TOWN, 0)
#endif
    gSaveContext.save.entrance = DSCE_TB_ENTRANCE;
    gSaveContext.save.cutsceneIndex = 0;
    gSaveContext.save.playerForm = PLAYER_FORM_HUMAN;
    gSaveContext.save.hasTatl = true;
#if DSCE_TB_GRANT_MASK
    /* the Brother's Mask on human C-LEFT so input scripts can equip it headlessly with a
     * CL press (TB_GRANT_MASK=0 builds a variant that must EARN it from the pickup) */
    gSaveContext.save.saveInfo.inventory.items[SLOT_MASK_CIRCUS_LEADER] = ITEM_MASK_CIRCUS_LEADER;
    BUTTON_ITEM_EQUIP(0, EQUIP_SLOT_C_LEFT) = ITEM_MASK_CIRCUS_LEADER;
    C_SLOT_EQUIP(0, EQUIP_SLOT_C_LEFT) = SLOT_MASK_CIRCUS_LEADER;
#else
    /* the earn-it build: the debug save owns every mask -- take the Brother's Mask (the
     * fully-replaced Troupe Leader slot) away so the Peach rite is the only way to it */
    gSaveContext.save.saveInfo.inventory.items[SLOT_MASK_CIRCUS_LEADER] = ITEM_NONE;
    {
        s32 dsceBtn;
        for (dsceBtn = EQUIP_SLOT_C_LEFT; dsceBtn <= EQUIP_SLOT_C_RIGHT; dsceBtn++) {
            if (BUTTON_ITEM_EQUIP(0, dsceBtn) == ITEM_MASK_CIRCUS_LEADER) {
                BUTTON_ITEM_EQUIP(0, dsceBtn) = ITEM_NONE;
            }
        }
    }
#endif
    /* NB: the macros declare an internal 'GameState* state' -- caller var must NOT be
     * named 'state' (self-init shadowing bug cost a debugging session). */
    STOP_GAMESTATE(gs);
    SET_NEXT_GAMESTATE(gs, Play_Init, sizeof(PlayState));
    return 1;
#else
    (void)gs;
    return 0;
#endif
}

static Actor* sDsceSpikeActor = NULL; /* owned here: spawned by the hook, killed on unequip */
static int sDsceViaMask = 0;          /* how the takeover was activated: only mask-activated
                                       * takeovers are torn down by mask removal (the L+R+Z
                                       * debug path must not be killed by the mask watch) */

static void Dsce_SpawnTakeover(PlayState* play) {
    Player* player = GET_PLAYER(play);

    sDsceSpikeActor = Actor_Spawn(&play->actorCtx, play, ACTOR_DSCE_MARIO, player->actor.world.pos.x,
                                  player->actor.world.pos.y, player->actor.world.pos.z, 0, 0, 0, 0);
}

/* [DSCE CAMERA] SM64-style follow cam, ported 1:1 from the PC's Dsce_MarioFollowCam
 * (2s2h z_play.c:1382): auto-aligns behind Mario with Lakitu lag, smoothed eye, look-at
 * above his feet. Runs AFTER Camera_Update (own hook point) so it overrides what MM
 * computed. EXTENSION over the PC: the D-PAD (unused by vanilla MM gameplay -- verified
 * zero reads in z_player/z_play) is Mario's camera: left/right orbit, up/down steps the
 * distance through notches. The one modal exception is Mario's ocarina: like the PC
 * implementation, keep this camera alive, freeze its orbit, turn Mario toward it, and
 * apply the separately tuned singing look-at offset. Other cutscenes/textboxes release
 * cleanly to MM's camera. */
void Dsce_CameraHook(PlayState* play) {
    static s16 sCamYaw;
    static Vec3f sEye;
    static int sCamInit = 0;
    static s16 sOrbitOffset = 0;
    static s8 sDistNotch = 1; /* 0=close 1=normal 2=far */
    static s16 sOcarinaYaw;
    static int sOcarinaYawInit = 0;
    static const f32 sNotchMul[3] = { 0.6f, 1.0f, 1.6f };
    Camera* cam = GET_ACTIVE_CAM(play);
    Player* player = GET_PLAYER(play);
    Input* input = &play->state.input[0];
    f32 dist;
    f32 camHeight;
    f32 lookHeight;
    s16 behind;
    Vec3f goalEye;
    f32 dx;
    f32 dy;
    f32 dz;
    int ocarinaOut;

    if (!gDsceSpikeAlive || (cam == NULL) || (player == NULL)) {
        sCamInit = 0; /* release: MM's camera output stands */
        sOcarinaYawInit = 0;
        return;
    }
    ocarinaOut = (player->stateFlags2 & PLAYER_STATE2_USING_OCARINA) != 0;
    if (!ocarinaOut && (Play_InCsMode(play) || (play->msgCtx.msgMode != 0))) {
        sCamInit = 0;
        sOcarinaYawInit = 0;
        return;
    }
    if (ocarinaOut) {
        /* PC parity: the player pivots to the held camera, rather than making the
         * follow camera chase behind the changing player yaw.  Keep our own yaw
         * because the neutral sandbox tick republishes its locomotion-facing yaw. */
        if (!sOcarinaYawInit) {
            sOcarinaYaw = player->actor.shape.rot.y;
            sOcarinaYawInit = 1;
        }
        if (DSCE_SingFaceCam) {
            s16 yawToCam = Math_Vec3f_Yaw(&player->actor.world.pos, &cam->eye);
            Math_ScaledStepToS(&sOcarinaYaw, yawToCam, DSCE_SingTurnSpeed);
            player->actor.shape.rot.y = sOcarinaYaw;
            player->actor.world.rot.y = sOcarinaYaw;
            if (sDsceSpikeActor != NULL) {
                sDsceSpikeActor->shape.rot.y = sOcarinaYaw;
            }
        }
    } else {
        sOcarinaYawInit = 0;
        /* d-pad camera (Mario-form only; vanilla MM never reads it) */
        if (CHECK_BTN_ALL(input->cur.button, BTN_DLEFT)) {
            sOrbitOffset += DSCE_MarioCamOrbitStep;
        }
        if (CHECK_BTN_ALL(input->cur.button, BTN_DRIGHT)) {
            sOrbitOffset -= DSCE_MarioCamOrbitStep;
        }
        if (CHECK_BTN_ALL(input->press.button, BTN_DUP) && (sDistNotch > 0)) {
            sDistNotch--;
        }
        if (CHECK_BTN_ALL(input->press.button, BTN_DDOWN) && (sDistNotch < 2)) {
            sDistNotch++;
        }
        sOrbitOffset -= sOrbitOffset / 16; /* manual orbit decays back behind Mario */
    }

    /* The approved PC instrument view used its saved 212/49/11 camera, not the
     * much taller N64 gameplay camera. Singing ignores the gameplay distance
     * notch so its composition is stable and reproducible. */
    if (ocarinaOut) {
        dist = DSCE_MarioOcarinaCamDist;
        camHeight = DSCE_MarioOcarinaCamHeight;
        lookHeight = DSCE_MarioOcarinaCamLook;
    } else {
        dist = DSCE_MarioCamDist * sNotchMul[sDistNotch];
        camHeight = DSCE_MarioCamHeight;
        lookHeight = DSCE_MarioCamLook;
    }
    behind = (s16)(player->actor.shape.rot.y + 0x8000 + sOrbitOffset);
    if (!sCamInit) {
        sCamYaw = behind;
    }
    if (!ocarinaOut) {
        sCamYaw += (s16)(behind - sCamYaw) / DSCE_MarioCamYawLag;
    }
    goalEye.x = player->actor.world.pos.x + Math_SinS(sCamYaw) * dist;
    goalEye.y = player->actor.world.pos.y + camHeight;
    goalEye.z = player->actor.world.pos.z + Math_CosS(sCamYaw) * dist;
    if (!sCamInit) {
        sEye = goalEye;
        sCamInit = 1;
    }
    sEye.x += (goalEye.x - sEye.x) * (DSCE_MarioCamLerp / 100.0f);
    sEye.y += (goalEye.y - sEye.y) * (DSCE_MarioCamLerp / 100.0f);
    sEye.z += (goalEye.z - sEye.z) * (DSCE_MarioCamLerp / 100.0f);
    cam->eye = sEye;
    cam->eyeNext = sEye;
    cam->at.x = player->actor.world.pos.x;
    cam->at.y = player->actor.world.pos.y + lookHeight;
    cam->at.z = player->actor.world.pos.z;
    if (ocarinaOut) {
        cam->at.x += DSCE_MarioOcarinaCamX;
        cam->at.y += DSCE_MarioOcarinaCamY;
        cam->at.z += DSCE_MarioOcarinaCamZ;
    }
    /* PC pins this explicitly; MM cutscene cameras may leave a different up
     * vector behind when our post-Camera_Update override takes authority. */
    cam->up.x = 0.0f;
    cam->up.y = 1.0f;
    cam->up.z = 0.0f;

    dx = sEye.x - player->actor.world.pos.x;
    dy = sEye.y - player->actor.world.pos.y;
    dz = sEye.z - player->actor.world.pos.z;
    gDsceTelemetry.camDist = (u32)(sqrtf(dx * dx + dy * dy + dz * dz) * 10.0f);
}

void Dsce_PlayUpdateHook(PlayState* play) {
    Input* input = &play->state.input[0];

    gDscePlayFrame++;
#if DSCE_DBG_GAMEPLAY
    {
        Player* probePlayer = GET_PLAYER(play);
        gDsceLifecycleProbe[0] = gDscePlayFrame;
        gDsceLifecycleProbe[1] = (probePlayer != NULL) ? probePlayer->stateFlags1 : 0;
        gDsceLifecycleProbe[2] = (probePlayer != NULL) ? probePlayer->stateFlags2 : 0;
        gDsceLifecycleProbe[3] = ((u32)(u8)play->roomCtx.curRoom.num << 24) |
                                 ((u32)(u8)play->roomCtx.prevRoom.num << 16) |
                                 ((u32)(Play_InCsMode(play) ? 1 : 0) << 8) |
                                 ((u32)play->msgCtx.msgMode & 0xFF);
        gDsceLifecycleProbe[4] = gDsceSpikeAlive;
        gDsceLifecycleProbe[5] = (gDsceSpikeAlive && (sDsceSpikeActor != NULL))
                                     ? (((u32)sDsceSpikeActor->freezeTimer << 16) |
                                        ((sDsceSpikeActor->update != NULL) ? 1 : 0))
                                     : 0;
        gDsceLifecycleProbe[6] = (gDsceSpikeAlive && (sDsceSpikeActor != NULL))
                                     ? sDsceSpikeActor->flags
                                     : 0;
        gDsceLifecycleProbe[7] = ((u32)((probePlayer != NULL) ? (u8)probePlayer->transformation : 0xFF)) |
                                 ((u32)(sDsceViaMask ? 1 : 0) << 8) |
                                 ((u32)(u8)play->transitionTrigger << 16) |
                                 ((u32)play->transitionMode << 24);
    }
#endif
    if (gSaveContext.save.playerForm == PLAYER_FORM_MARIO) {
        gDsceDmaLogArmed = 1;
    }

    /* [DSCE] Mario's mask-on scream, PC timing: the transform-voice cue armed this countdown
     * (MarioScreamDelay ms of lead-in silence, PC parity); fire the scream when it hits zero. */
    if ((gDsceScreamDelayFrames > 0) && (--gDsceScreamDelayFrames == 0)) {
        extern void Dsce_AdapterPlayVoice(int kind);
        Dsce_AdapterPlayVoice(4); /* DSCE_VOICE_FALL: the "waaaooow" scream */
    }

    /* keep the adapter authority pointing at the live PlayState every frame, so Mario's voice can
     * play during the transform CUTSCENE (the scream) before the takeover actor exists yet. */
    { extern PlayState* gDsceAuthorityPlay; gDsceAuthorityPlay = play; }

    { /* [DSCE LOG] per-frame player+cutscene state (the crux of the transform freeze debug) */
        Player* p = GET_PLAYER(play);
        Dsce_Log("hook.tick",
                 (p != NULL) ? (s32)p->transformation : -1,
                 (p != NULL) ? (s32)p->stateFlags1 : 0,
                 Play_InCsMode(play) ? 1 : 0,
                 gDsceSpikeAlive);
    }

    /* [DSCE] Song of Healing LATCH. The statue actor gets frozen by Actor_UpdateAll for ~57
     * frames around song completion (textbox/cutscene state flags) -- exactly the window when
     * ocarinaMode == OCARINA_MODE_EVENT flashes by -- so it can NEVER see the event itself,
     * whatever its category/flags. This hook runs straight from Play_Update (never frozen):
     * latch the event with a grace TTL; the statue consumes it once it thaws. */
    if ((play->msgCtx.ocarinaMode == OCARINA_MODE_EVENT) &&
        (play->msgCtx.lastPlayedSong == OCARINA_SONG_HEALING)) {
        gDsceSongHealLatch = 100;
    } else if (gDsceSongHealLatch > 0) {
        gDsceSongHealLatch--;
    }

#if DSCE_DBG_GAMEPLAY
    /* tag 0: the exact message/song boundary seen by the unfrozen Play_Update hook.
     * Emitted only while the rite is relevant so a crash capture retains the whole
     * transition even when the host polls the fixed-size ring a few seconds later. */
    {
        extern int gDsceStatueUp;
        if (gDsceStatueUp && (((play->msgCtx.ocarinaMode | play->msgCtx.msgMode) != 0) ||
                             (gDsceSongHealLatch > 0))) {
            Dsce_Fh(7, 0, play->msgCtx.ocarinaMode, play->msgCtx.msgMode,
                    play->msgCtx.lastPlayedSong, gDsceSongHealLatch);
        }
    }
#endif

    { /* [DSCE LOG] rite-freeze diagnostics from OUTSIDE the actor freezer (this hook is called
         straight from Play_Update): what states gate Actor_UpdateAll while the ocarina runs */
        extern int gDsceStatueUp;
        Player* dp = GET_PLAYER(play);
        static u8 sDsceOcLog = 0;
        /* EVERY frame while the ocarina/message flow is live: mode transitions are too brief
         * for throttled sampling. a=ocarinaMode|msgMode<<8, b=lastSong|ocarinaAction<<8 */
        if (gDsceStatueUp && (dp != NULL) &&
            (((play->msgCtx.ocarinaMode | play->msgCtx.msgMode) != 0) || ((++sDsceOcLog & 31) == 0))) {
            Dsce_Log("oc.state", (s32)(play->msgCtx.ocarinaMode | ((s32)play->msgCtx.msgMode << 8)),
                     (s32)(play->msgCtx.lastPlayedSong | ((s32)play->msgCtx.ocarinaAction << 8)),
                     gDsceSongHealLatch, (s32)dp->stateFlags2);
        }
    }
#if DSCE_XTEST
    /* [DSCE XTEST] the cross-game arena build: auto-spawn the takeover at the SM64 spawn
     * point (no mask dance -- the SANDBOX is what the oracle comparison measures), then
     * seed MarioState with the EXACT spawn constants so both games start bit-identically. */
    {
#include "dsce_xtest_arena.h"
        Player* xp = GET_PLAYER(play);
        if (!gDsceSpikeAlive && (play->state.frames > 30) && (xp != NULL)) {
            extern float gDsceMmScale;
            extern void Dsce_XtestSeedMario(void); /* kernel-side: exact spawn constants */
            xp->actor.world.pos.x = DSCE_XTEST_SPAWN_X / gDsceMmScale;
            xp->actor.world.pos.y = DSCE_XTEST_SPAWN_Y / gDsceMmScale;
            xp->actor.world.pos.z = DSCE_XTEST_SPAWN_Z / gDsceMmScale;
            xp->actor.shape.rot.y = DSCE_XTEST_SPAWN_YAW;
            Dsce_SpawnTakeover(play);
            if (gDsceSpikeAlive) {
                Dsce_XtestSeedMario();
            }
        }
    }
#endif

#if DSCE_DBG_AUDIO
    Dsce_FhPollAudio();
#endif
    gDsceTelemetry.maskItem = gSaveContext.save.saveInfo.inventory.items[SLOT_MASK_CIRCUS_LEADER];
    {
        extern int gDsceStatueUp;
        extern int gDscePickupUp;
        gDsceTelemetry.questState =
            (gDsceTelemetry.maskItem == ITEM_MASK_CIRCUS_LEADER) ? 3 : (gDscePickupUp ? 2 : (gDsceStatueUp ? 1 : 0));
    }

    /* THE BROTHER'S MASK: donning it runs MM's real transformation cutscene (raise + flash +
     * Mario scream) via func_808388B8(PLAYER_FORM_MARIO); the scene then reloads with the player
     * in PLAYER_FORM_MARIO. `this->transformation` only becomes MARIO in Player_Init after that
     * reload -- so this watch fires AFTER the cutscene, never during it (Link stays visible for
     * the raise). mask off -> transform back to human -> transformation != MARIO -> Actor_Kill
     * tears the takeover down. Scene transitions kill the actor; still-Mario respawns it here. */
    {
        Player* maskPlayer = GET_PLAYER(play);
        /* Spawn the takeover only once the transformation is COMPLETE: transformation becomes MARIO
         * inside Player_Init (mid-cutscene), but Player_Action_87 keeps PLAYER_STATE1_2 set until the
         * post-transform "settle" animation finishes (the player moves the stick). Spawning during
         * that window puppets the player and freezes Action_87 -> the cutscene never ends (CsMode
         * stuck). Gate on BOTH !PLAYER_STATE1_2 AND !Play_InCsMode: the whole transform (raise anim,
         * flash, re-init, settle) runs inside cutscene mode; PLAYER_STATE1_2 covers that whole
         * window (Action_87 clears it the same frame it ends the cutscene). Do NOT gate on
         * Play_InCsMode here: that killed the takeover during EVERY cutscene -- ocarina use,
         * entrance pans, exits -- so Link flashed back each time. The takeover stays alive
         * through those; its own update idles Mario while a cutscene/song UI runs. */
        int maskOn = (maskPlayer != NULL) && (maskPlayer->transformation == PLAYER_FORM_MARIO) &&
                     !(maskPlayer->stateFlags1 & PLAYER_STATE1_2);

        if (!gDsceSpikeAlive) {
            sDsceSpikeActor = NULL; /* engine may have freed it (scene change) */
        }
        if (maskOn && !gDsceSpikeAlive) {
            Dsce_Log("hook.spawn", (maskPlayer != NULL) ? (s32)maskPlayer->transformation : -1,
                     (maskPlayer != NULL) ? (s32)maskPlayer->stateFlags1 : 0, Play_InCsMode(play) ? 1 : 0, 0);
            Dsce_SpawnTakeover(play);
            sDsceViaMask = 1;
        } else if (!maskOn && gDsceSpikeAlive && sDsceViaMask && (sDsceSpikeActor != NULL)) {
            Dsce_Log("hook.kill", (maskPlayer != NULL) ? (s32)maskPlayer->transformation : -1,
                     (maskPlayer != NULL) ? (s32)maskPlayer->stateFlags1 : 0, Play_InCsMode(play) ? 1 : 0, 0);
            Actor_Kill(sDsceSpikeActor);
            sDsceSpikeActor = NULL;
            sDsceViaMask = 0;
        }
    }

    /* REAL enemy-hit knockback (goal 04): when an MM enemy's AC collider hits the
     * puppeted player this frame (and he's not mid-invuln), drive the SM64 knockback
     * from the actual damage + attacker direction. Same globals the driver consumes;
     * replaces the old debug-only L+R+B combo (now testboot-gated below). */
    if (gDsceSpikeAlive) {
        extern int gDsceMarioKbReq;
        extern s16 gDsceMarioKbYaw;
        extern int gDsceMarioKbDmg;
        Player* hitPlayer = GET_PLAYER(play);
        if ((hitPlayer != NULL) && (hitPlayer->cylinder.base.acFlags & AC_HIT) &&
            (hitPlayer->invincibilityTimer == 0)) {
            Actor* attacker = hitPlayer->cylinder.base.ac;
            gDsceMarioKbYaw = (attacker != NULL)
                                  ? Actor_WorldYawTowardActor(&hitPlayer->actor, attacker)
                                  : hitPlayer->actor.shape.rot.y;
            gDsceMarioKbDmg = (hitPlayer->actor.colChkInfo.damage > 0)
                                  ? hitPlayer->actor.colChkInfo.damage
                                  : 1;
            gDsceMarioKbReq = 1;
        }
    }

    /* Deku-flower ground-pound launch (goal 04): while Mario is ground-pounding, a
     * nearby Deku flower (Obj_Etcetera) launches him in an SM64 spinning bounce. The
     * driver consumes gDsceMarioBounceReq into ACT_TWIRLING. */
    if (gDsceSpikeAlive) {
        extern int gDsceMarioGroundPounding;
        extern int gDsceMarioBounceReq;
        Player* dp = GET_PLAYER(play);
        if (gDsceMarioGroundPounding && !gDsceMarioBounceReq && (dp != NULL)) {
            Actor* a = play->actorCtx.actorLists[ACTORCAT_BG].first;
            while (a != NULL) {
                if (a->id == ACTOR_OBJ_ETCETERA) {
                    f32 ddx = dp->actor.world.pos.x - a->world.pos.x;
                    f32 ddz = dp->actor.world.pos.z - a->world.pos.z;
                    f32 ddy = dp->actor.world.pos.y - a->world.pos.y;
                    if (((ddx * ddx + ddz * ddz) < (60.0f * 60.0f)) && (ddy < 60.0f) && (ddy > -40.0f)) {
                        gDsceMarioBounceReq = 1;
                        break;
                    }
                }
                a = a->next;
            }
        }
    }

#if DSCE_TESTBOOT
    /* debug knockback (L+R+B), testboot only: drives the same path for headless testing
     * without scripting a real enemy encounter. */
    if (gDsceSpikeAlive && CHECK_BTN_ALL(input->cur.button, BTN_L | BTN_R) &&
        CHECK_BTN_ALL(input->press.button, BTN_B)) {
        extern int gDsceMarioKbReq;
        extern s16 gDsceMarioKbYaw;
        extern int gDsceMarioKbDmg;
        Player* kbPlayer = GET_PLAYER(play);
        gDsceMarioKbYaw = kbPlayer->actor.shape.rot.y;
        gDsceMarioKbDmg = 1;
        gDsceMarioKbReq = 1;
        if (gSaveContext.save.saveInfo.playerData.health > 0x10) {
            gSaveContext.save.saveInfo.playerData.health -= 0x10;
        }
    }
#endif
    /* THE ACQUISITION (Song of Healing): a stone Peach statue waits at the Laundry
     * Pool; the Song of Healing beside her heals the trapped soul into the Brother's
     * Mask pickup. Statue placement = scene entry + PeachStatue{X,Y,Z} (tuning). */
    {
        static int sDsceStatueAlive = 0;
        extern int gDsceStatueDied;
        if (gDsceStatueDied) {
            sDsceStatueAlive = 0;
            gDsceStatueDied = 0;
        }
        if ((play->sceneId == SCENE_ALLEY) && !sDsceStatueAlive && (play->state.frames > 20) &&
            (gSaveContext.save.saveInfo.inventory.items[SLOT_MASK_CIRCUS_LEADER] != ITEM_MASK_CIRCUS_LEADER)) {
            {
                /* [DSCE] INHERITED from the PC bake (dsce_peach_tuning.h): the statue stands at
                 * the ABSOLUTE world spot the user placed her on the PC, facing PeachFaceDeg --
                 * not relative to wherever the player entered. Floor-snap kept as a safety. */
                f32 sx = DSCE_PeachWorldX;
                f32 sy = DSCE_PeachWorldY;
                f32 sz = DSCE_PeachWorldZ;
                /* NO floor snap: the baked PeachWorldY IS her placed floor (the PC bake). The old
                 * raycast fires at ~frame 22, before the walkway's dyna collision registers, and
                 * snapped her 23 units down onto the ground UNDER the walkway (sunken statue). */
                if (Actor_Spawn(&play->actorCtx, play, ACTOR_DSCE_MARIO, sx, sy, sz, 0,
                                (s16)(DSCE_PeachFaceDeg * (65536.0f / 360.0f)), 0, 2) != NULL) {
                    sDsceStatueAlive = 1;
                }
            }
        }
    }

#if DSCE_TESTBOOT
    /* debug: L+R+A = "the Song of Healing just played" (headless rite testing) */
    if (CHECK_BTN_ALL(input->cur.button, BTN_L | BTN_R) &&
        CHECK_BTN_ALL(input->press.button, BTN_A)) {
        extern int gDsceDebugSong;
        gDsceDebugSong = 1;
    }
#endif

#if DSCE_TESTBOOT
    /* debug fallback: force the takeover without the mask (test ROMs only) */
    if (!gDsceSpikeAlive && CHECK_BTN_ALL(input->cur.button, BTN_L | BTN_R | BTN_Z)) {
        Dsce_SpawnTakeover(play);
        sDsceViaMask = 0;
    }
#endif
}
