/* [DSCE N64] Support TU for the vendored SM64 moveset kernel: global storage, spike-scope stubs,
 * and the collision shim that routes SM64's find_* queries to the MM BgCheck adapters
 * (dsce_adapters.c, MM-side). Derived from n64/src/sm64/UNDEF_SYMBOLS.txt -- every symbol here is
 * one the kernel actually references. Phase P: hazards/interaction/audio are stubbed; they get
 * real implementations in Phase 1/3. */
#include "../../dsce_config.h" /* DSCE_XTEST flag (generated by make mod) */
#include "sm64.h"
#include "types.h"
#include "game/mario.h"
#include "game/area.h"
#include "game/camera.h"
#include "game/level_update.h" /* struct HudDisplay + gHudDisplay extern */
#include "game/memory.h"
#include "engine/surface_collision.h"
#include "include/surface_terrains.h"

/* ---- MM-side adapters (dsce_adapters.c; flat-args ABI, MM units handled inside) ---- */
extern int Dsce_AdapterFindFloor(float sx, float sy, float sz, float* outHeight, float* outNx,
                                 float* outNy, float* outNz, int* outDanger);
extern int Dsce_AdapterFindWalls(float sx, float sy, float sz, float prevSx, float prevSy,
                                 float prevSz, float radius, float* outDispX, float* outDispZ,
                                 float* outNx, float* outNy, float* outNz, int* outDanger);
extern int Dsce_AdapterFindWater(float sx, float sz, float* outSurf);
extern int Dsce_AdapterFindCeil(float sx, float sy, float sz, float* outHeight);

/* ---- global storage the kernel expects (normally game_init/area/save_file provide these) ---- */
/* exported (not static) so the linker map carries its address: the cross-game metamorphic
 * rig (goal 10) reads this EXACT struct from RDRAM and compares it bit-for-bit against the
 * real SM64 ROM's gMarioStates[0] -- same layout, same units, same MIPS float code. */
struct MarioState gDsceMarioState;
struct MarioState* gMarioState = &gDsceMarioState;
struct Object* gMarioObject = NULL; /* driver points it at its scaffold Object on init */
struct Controller gControllers[3];
struct Controller* gPlayer1Controller = &gControllers[0];
struct MarioBodyState gBodyStates[2];
struct PlayerCameraState gPlayerCameraState[2];
struct SpawnInfo gPlayerSpawnInfos[1];
struct SpawnInfo* gMarioSpawnInfo = &gPlayerSpawnInfos[0];
static struct Area sDsceArea;
struct Area* gCurrentArea = &sDsceArea;
struct HudDisplay gHudDisplay;
u32 gAudioRandom = 0x12345678;
u32 gGlobalTimer = 0;
s16 gCurrLevelNum = 16; /* LEVEL_CASTLE_GROUNDS-ish; only read for cap/level checks */
s16 gCurrSaveFileNum = 1;
s32 gDebugLevelSelect = 0;
s32 gShowDebugText = 0;
s32 gSpecialTripleJump = 0;
s16 gCameraMovementFlags = 0;
f32 gGlobalSoundSource[3] = { 0.0f, 0.0f, 0.0f };
Vec3f gVec3fZero = { 0.0f, 0.0f, 0.0f };
u8 gMarioAnimsBuf[0x100]; /* only the address is taken; load_patchable_table is stubbed */

/* [DSCE N64] SAFE fake animation: set_mario_animation dereferences m->animList->bufTarget
 * unconditionally (real anims are Phase 2). Zero deltas, 2-frame loop, valid pointers --
 * the anim ID still lands in animInfo.animID, which is all the future draw hook reads.
 * (A NULL animList wedged the console inside ACT_START_CROUCHING on the first Z-held tick.) */
static s16 sDsceFakeAnimValues[64];
static u16 sDsceFakeAnimIndex[128];
static struct Animation sDsceFakeAnim = { 0, 1, 0, 0, 2, 0, sDsceFakeAnimValues, sDsceFakeAnimIndex, 0 };
struct DmaHandlerList gDsceAnimList = { NULL, NULL, &sDsceFakeAnim };
uintptr_t bhvJumpingBox[] = { 0 };
uintptr_t bhvNormalCap[] = { 0 };
uintptr_t bhvTree[] = { 0 };      /* pole/tree behaviors: no SM64 objects exist in MM, */
uintptr_t bhvGiantPole[] = { 0 }; /* so these are never matched -- address-only */
uintptr_t bhvKoopaShellUnderwater[] = { 0 };
s16 gCurrAreaIndex = 1;

void* virtual_to_segmented(u32 segment, const void* addr) {
    return (void*) addr; /* no segmented memory on the DSCE side */
}


/* ================= DSCE_XTEST: the cross-game arena collision engine =================
 * SM64's ORIGINAL surface algorithms (surface_load read_surface_data + surface_collision
 * find_floor/find_ceil/find_wall_collisions, ported verbatim incl. s16 position
 * truncation, the 78-unit buffers, first-hit-breaks and the vertex1-height sort) running
 * over the generated arena tables -- the SAME triangles the sm64-xtest oracle ROM walks.
 * The find_* shims below route here under DSCE_XTEST, so cross-game runs compare the two
 * games on identical geometry with identical collision semantics. */
#if DSCE_XTEST
#include "../../dsce_xtest_arena.h"

static struct Surface sXtSurf[DSCE_XTEST_NUM_TRIS];
static struct Surface* sXtFloors[DSCE_XTEST_NUM_TRIS];
static struct Surface* sXtCeils[DSCE_XTEST_NUM_TRIS];
static struct Surface* sXtWalls[DSCE_XTEST_NUM_TRIS];
static s32 sXtNumFloors, sXtNumCeils, sXtNumWalls;
static s32 sXtInit = 0;

static void xt_insert_sorted(struct Surface** arr, s32* n, struct Surface* surf, s32 sortDir) {
    /* surface_load add_surface_to_cell: priority = vertex1[1] * sortDir, descending;
     * equal priorities keep insertion order (the new node goes after its equals). */
    s32 pri = surf->vertex1[1] * sortDir;
    s32 i = 0;
    s32 j;

    while ((i < *n) && (arr[i]->vertex1[1] * sortDir >= pri)) {
        i++;
    }
    for (j = *n; j > i; j--) {
        arr[j] = arr[j - 1];
    }
    arr[i] = surf;
    (*n)++;
}

static void xt_init(void) {
    s32 t;

    if (sXtInit) {
        return;
    }
    sXtInit = 1;
    for (t = 0; t < DSCE_XTEST_NUM_TRIS; t++) {
        struct Surface* surface = &sXtSurf[t];
        s32 x1 = sDsceXtestVerts[sDsceXtestTris[t][0]][0];
        s32 y1 = sDsceXtestVerts[sDsceXtestTris[t][0]][1];
        s32 z1 = sDsceXtestVerts[sDsceXtestTris[t][0]][2];
        s32 x2 = sDsceXtestVerts[sDsceXtestTris[t][1]][0];
        s32 y2 = sDsceXtestVerts[sDsceXtestTris[t][1]][1];
        s32 z2 = sDsceXtestVerts[sDsceXtestTris[t][1]][2];
        s32 x3 = sDsceXtestVerts[sDsceXtestTris[t][2]][0];
        s32 y3 = sDsceXtestVerts[sDsceXtestTris[t][2]][1];
        s32 z3 = sDsceXtestVerts[sDsceXtestTris[t][2]][2];
        f32 nx = (y2 - y1) * (z3 - z2) - (z2 - z1) * (y3 - y2);
        f32 ny = (z2 - z1) * (x3 - x2) - (x2 - x1) * (z3 - z2);
        f32 nz = (x2 - x1) * (y3 - y2) - (y2 - y1) * (x3 - x2);
        f32 mag = sqrtf(nx * nx + ny * ny + nz * nz);
        s32 minY = y1;
        s32 maxY = y1;

        if (y2 < minY) { minY = y2; }
        if (y3 < minY) { minY = y3; }
        if (y2 > maxY) { maxY = y2; }
        if (y3 > maxY) { maxY = y3; }
        if (mag < 0.0001f) {
            continue;
        }
        mag = (f32)(1.0 / mag);
        nx *= mag;
        ny *= mag;
        nz *= mag;
        surface->vertex1[0] = x1; surface->vertex1[1] = y1; surface->vertex1[2] = z1;
        surface->vertex2[0] = x2; surface->vertex2[1] = y2; surface->vertex2[2] = z2;
        surface->vertex3[0] = x3; surface->vertex3[1] = y3; surface->vertex3[2] = z3;
        surface->normal.x = nx;
        surface->normal.y = ny;
        surface->normal.z = nz;
        surface->originOffset = -(nx * x1 + ny * y1 + nz * z1);
        surface->lowerY = minY - 5;
        surface->upperY = maxY + 5;
        surface->type = sDsceXtestTris[t][3] ? SURFACE_BURNING : SURFACE_DEFAULT;
        surface->flags = 0;
        surface->room = 0;
        if (ny > 0.01f) {
            xt_insert_sorted(sXtFloors, &sXtNumFloors, surface, 1);
        } else if (ny < -0.01f) {
            xt_insert_sorted(sXtCeils, &sXtNumCeils, surface, -1);
        } else {
            if (surface->normal.x < -0.707f || surface->normal.x > 0.707f) {
                surface->flags |= SURFACE_FLAG_X_PROJECTION;
            }
            sXtWalls[sXtNumWalls++] = surface;
        }
    }
}

#define XT_LEVEL_BOUNDARY_MAX 0x2000
#define XT_FLOOR_LOWER_LIMIT -11000.0f
#define XT_CELL_HEIGHT_LIMIT 20000.0f

static struct Surface* xt_find_floor_from_list(s32 x, s32 y, s32 z, f32* pheight) {
    struct Surface* floor = NULL;
    s32 i;

    for (i = 0; i < sXtNumFloors; i++) {
        struct Surface* surf = sXtFloors[i];
        s32 x1 = surf->vertex1[0];
        s32 z1 = surf->vertex1[2];
        s32 x2 = surf->vertex2[0];
        s32 z2 = surf->vertex2[2];
        s32 x3, z3;
        f32 nx, ny, nz, oo, height;

        if ((z1 - z) * (x2 - x1) - (x1 - x) * (z2 - z1) < 0) {
            continue;
        }
        x3 = surf->vertex3[0];
        z3 = surf->vertex3[2];
        if ((z2 - z) * (x3 - x2) - (x2 - x) * (z3 - z2) < 0) {
            continue;
        }
        if ((z3 - z) * (x1 - x3) - (x3 - x) * (z1 - z3) < 0) {
            continue;
        }
        nx = surf->normal.x;
        ny = surf->normal.y;
        nz = surf->normal.z;
        oo = surf->originOffset;
        if (ny == 0.0f) {
            continue;
        }
        height = -(x * nx + nz * z + oo) / ny;
        if (y - (height + -78.0f) < 0.0f) {
            continue;
        }
        *pheight = height;
        floor = surf;
        break;
    }
    return floor;
}

static struct Surface* xt_find_ceil_from_list(s32 x, s32 y, s32 z, f32* pheight) {
    struct Surface* ceil = NULL;
    s32 i;

    for (i = 0; i < sXtNumCeils; i++) {
        struct Surface* surf = sXtCeils[i];
        s32 x1 = surf->vertex1[0];
        s32 z1 = surf->vertex1[2];
        s32 x2 = surf->vertex2[0];
        s32 z2 = surf->vertex2[2];
        s32 x3, z3;
        f32 nx, ny, nz, oo, height;

        /* ceilings use the REVERSED winding tests (original find_ceil_from_list) */
        if ((z1 - z) * (x2 - x1) - (x1 - x) * (z2 - z1) > 0) {
            continue;
        }
        x3 = surf->vertex3[0];
        z3 = surf->vertex3[2];
        if ((z2 - z) * (x3 - x2) - (x2 - x) * (z3 - z2) > 0) {
            continue;
        }
        if ((z3 - z) * (x1 - x3) - (x3 - x) * (z1 - z3) > 0) {
            continue;
        }
        nx = surf->normal.x;
        ny = surf->normal.y;
        nz = surf->normal.z;
        oo = surf->originOffset;
        if (ny == 0.0f) {
            continue;
        }
        height = -(x * nx + nz * z + oo) / ny;
        if (y - (height - -78.0f) > 0.0f) {
            continue;
        }
        *pheight = height;
        ceil = surf;
        break;
    }
    return ceil;
}

static s32 xt_find_wall_collisions(struct WallCollisionData* data) {
    struct WallCollisionData* col = data;
    f32 offset;
    f32 radius = col->radius;
    f32 x = col->x;
    f32 y = col->y + col->offsetY;
    f32 z = col->z;
    s32 numCols = 0;
    s32 i;

    if (radius > 200.0f) {
        radius = 200.0f;
    }
    col->numWalls = 0;
    for (i = 0; i < sXtNumWalls; i++) {
        struct Surface* surf = sXtWalls[i];
        f32 px = x, pz = z;
        f32 w1, w2, w3, y1, y2, y3;

        if (y < surf->lowerY || y > surf->upperY) {
            continue;
        }
        offset = surf->normal.x * x + surf->normal.y * y + surf->normal.z * z + surf->originOffset;
        if (offset < -radius || offset > radius) {
            continue;
        }
        if (surf->flags & SURFACE_FLAG_X_PROJECTION) {
            w1 = -surf->vertex1[2]; w2 = -surf->vertex2[2]; w3 = -surf->vertex3[2];
            y1 = surf->vertex1[1];  y2 = surf->vertex2[1];  y3 = surf->vertex3[1];
            if (surf->normal.x > 0.0f) {
                if ((y1 - y) * (w2 - w1) - (w1 - -pz) * (y2 - y1) > 0.0f) { continue; }
                if ((y2 - y) * (w3 - w2) - (w2 - -pz) * (y3 - y2) > 0.0f) { continue; }
                if ((y3 - y) * (w1 - w3) - (w3 - -pz) * (y1 - y3) > 0.0f) { continue; }
            } else {
                if ((y1 - y) * (w2 - w1) - (w1 - -pz) * (y2 - y1) < 0.0f) { continue; }
                if ((y2 - y) * (w3 - w2) - (w2 - -pz) * (y3 - y2) < 0.0f) { continue; }
                if ((y3 - y) * (w1 - w3) - (w3 - -pz) * (y1 - y3) < 0.0f) { continue; }
            }
        } else {
            w1 = surf->vertex1[0]; w2 = surf->vertex2[0]; w3 = surf->vertex3[0];
            y1 = surf->vertex1[1]; y2 = surf->vertex2[1]; y3 = surf->vertex3[1];
            if (surf->normal.z > 0.0f) {
                if ((y1 - y) * (w2 - w1) - (w1 - px) * (y2 - y1) > 0.0f) { continue; }
                if ((y2 - y) * (w3 - w2) - (w2 - px) * (y3 - y2) > 0.0f) { continue; }
                if ((y3 - y) * (w1 - w3) - (w3 - px) * (y1 - y3) > 0.0f) { continue; }
            } else {
                if ((y1 - y) * (w2 - w1) - (w1 - px) * (y2 - y1) < 0.0f) { continue; }
                if ((y2 - y) * (w3 - w2) - (w2 - px) * (y3 - y2) < 0.0f) { continue; }
                if ((y3 - y) * (w1 - w3) - (w3 - px) * (y1 - y3) < 0.0f) { continue; }
            }
        }
        /* the original pushes the queried position out along the wall's dominant axis */
        if (surf->flags & SURFACE_FLAG_X_PROJECTION) {
            x += surf->normal.x * (radius - offset);
        } else {
            z += surf->normal.z * (radius - offset);
        }
        if (col->numWalls < 4) {
            col->walls[col->numWalls++] = surf;
        }
        numCols++;
    }
    col->x = x;
    col->z = z;
    return numCols;
}
/* seed MarioState with the EXACT arena spawn constants (the hook's float roundtrip
 * through MM units would land ~1e-4 off; both games must start bit-identically) */
void Dsce_XtestSeedMario(void) {
    gMarioState->pos[0] = DSCE_XTEST_SPAWN_X;
    gMarioState->pos[1] = DSCE_XTEST_SPAWN_Y;
    gMarioState->pos[2] = DSCE_XTEST_SPAWN_Z;
    gMarioState->faceAngle[1] = DSCE_XTEST_SPAWN_YAW;
}

#endif /* DSCE_XTEST */
/* =============== end DSCE_XTEST collision engine =============== */

/* ---- collision shim: SM64 find_* -> MM BgCheck adapters ---- */
/* (gWaterSurfacePseudoFloor comes from mario_step.c, which the kernel vendors.) */
static struct Surface sDsceFloorSurf;
static struct Surface sDsceWallSurf;

f32 find_floor(f32 x, f32 y, f32 z, struct Surface** pfloor) {
    float h, nx, ny, nz;
    int danger = 0;
#if DSCE_XTEST
    { /* the arena IS the world: SM64's own algorithm over the shared triangles */
        s16 tx = (s16)(s32)x;
        s16 ty = (s16)(s32)y;
        s16 tz = (s16)(s32)z;
        f32 height = XT_FLOOR_LOWER_LIMIT;

        xt_init();
        *pfloor = NULL;
        if (tx <= -XT_LEVEL_BOUNDARY_MAX || tx >= XT_LEVEL_BOUNDARY_MAX ||
            tz <= -XT_LEVEL_BOUNDARY_MAX || tz >= XT_LEVEL_BOUNDARY_MAX) {
            return height;
        }
        *pfloor = xt_find_floor_from_list(tx, ty, tz, &height);
        return height;
    }
#endif
    if (Dsce_AdapterFindFloor(x, y, z, &h, &nx, &ny, &nz, &danger)) {
        /* lava/spike floors become SURFACE_BURNING so the vendored lava-boost reaction fires */
        sDsceFloorSurf.type = danger ? SURFACE_BURNING : SURFACE_DEFAULT;
        sDsceFloorSurf.normal.x = nx;
        sDsceFloorSurf.normal.y = ny;
        sDsceFloorSurf.normal.z = nz;
        sDsceFloorSurf.originOffset = -(nx * x + ny * h + nz * z);
        *pfloor = &sDsceFloorSurf;
        return h;
    }
    *pfloor = NULL;
    return -11000.0f;
}

f32 find_floor_height(f32 x, f32 y, f32 z) {
    struct Surface* s;
    return find_floor(x, y, z, &s);
}

static struct Surface sDsceCeilSurf;

f32 find_ceil(f32 x, f32 y, f32 z, struct Surface** pceil) {
    float h;
#if DSCE_XTEST
    {
        s16 tx = (s16)(s32)x;
        s16 ty = (s16)(s32)y;
        s16 tz = (s16)(s32)z;
        f32 height = XT_CELL_HEIGHT_LIMIT;

        xt_init();
        *pceil = NULL;
        if (tx <= -XT_LEVEL_BOUNDARY_MAX || tx >= XT_LEVEL_BOUNDARY_MAX ||
            tz <= -XT_LEVEL_BOUNDARY_MAX || tz >= XT_LEVEL_BOUNDARY_MAX) {
            return height;
        }
        *pceil = xt_find_ceil_from_list(tx, ty, tz, &height);
        return height;
    }
#endif
    if (Dsce_AdapterFindCeil(x, y, z, &h)) {
        sDsceCeilSurf.type = SURFACE_DEFAULT;
        sDsceCeilSurf.normal.x = 0.0f;
        sDsceCeilSurf.normal.y = -1.0f;
        sDsceCeilSurf.normal.z = 0.0f;
        sDsceCeilSurf.originOffset = h;
        *pceil = &sDsceCeilSurf;
        return h;
    }
    *pceil = NULL;
    return 20000.0f;
}

f32 find_water_level(f32 x, f32 z) {
    float surf;
#if DSCE_XTEST
    if (x >= DSCE_XTEST_WATER_X1 && x <= DSCE_XTEST_WATER_X2 &&
        z >= DSCE_XTEST_WATER_Z1 && z <= DSCE_XTEST_WATER_Z2) {
        return DSCE_XTEST_WATER_Y;
    }
    return -11000.0f;
#endif
    if (Dsce_AdapterFindWater(x, z, &surf)) {
        return surf;
    }
    return -11000.0f;
}

f32 find_poison_gas_level(f32 x, f32 z) {
    return -11000.0f;
}

s32 find_wall_collisions(struct WallCollisionData* colData) {
    float dx, dz, nx, ny, nz;
    float prevY;
    int danger;
#if DSCE_XTEST
    xt_init();
    return xt_find_wall_collisions(colData);
#endif
    colData->numWalls = 0;
    /* Every SM64 quarter-step queries a proposed local endpoint while gMarioState->pos
     * remains the last accepted endpoint.  Preserve that sweep for MM's wall solver;
     * passing next==prev disables its crossing test and leaves only shallow overlap
     * correction after Mario is already through the plane. */
    prevY = gMarioState->pos[1] + colData->offsetY;
    if (Dsce_AdapterFindWalls(colData->x, colData->y + colData->offsetY, colData->z,
                              gMarioState->pos[0], prevY, gMarioState->pos[2], colData->radius,
                              &dx, &dz, &nx, &ny, &nz, &danger)) {
        /* The adapter returns the ABSOLUTE pushed-out position (PC contract), not a delta.
         * (+= here doubled the position -> every walking quarter-step queried floor at 2x pos,
         * found void, and Mario could never move. Cost a long telemetry ladder to find.) */
        colData->x = dx;
        colData->z = dz;
        sDsceWallSurf.type = SURFACE_DEFAULT;
        sDsceWallSurf.normal.x = nx;
        sDsceWallSurf.normal.y = ny;
        sDsceWallSurf.normal.z = nz;
        colData->walls[0] = &sDsceWallSurf;
        colData->numWalls = 1;
    }
    return colData->numWalls;
}

s32 f32_find_wall_collision(f32* xPtr, f32* yPtr, f32* zPtr, f32 offsetY, f32 radius) {
    struct WallCollisionData col;
    col.x = *xPtr;
    col.y = *yPtr;
    col.z = *zPtr;
    col.offsetY = offsetY;
    col.radius = radius;
    find_wall_collisions(&col);
    *xPtr = col.x;
    *zPtr = col.z;
    return col.numWalls;
}

/* ---- other action groups: spike drops them to freefall (Phase 1 vendors the real files) ---- */
s32 mario_execute_cutscene_action(struct MarioState* m) {
    m->action = ACT_FREEFALL;
    m->actionState = 0;
    return FALSE;
}

/* ---- interaction.c surface (Phase 1 vendors the trimmed real file) ---- */
void mario_process_interactions(struct MarioState* m) {
}
void mario_handle_special_floors(struct MarioState* m) {
}
u32 mario_check_object_grab(struct MarioState* m) {
    return FALSE;
}
void mario_grab_used_object(struct MarioState* m) {
}
void mario_drop_held_object(struct MarioState* m) {
}
void mario_throw_held_object(struct MarioState* m) {
}
void mario_stop_riding_object(struct MarioState* m) {
}
void mario_stop_riding_and_holding(struct MarioState* m) {
}
void mario_blow_off_cap(struct MarioState* m, f32 capSpeed) {
}
/* (mario_bonk_reflection, mario_update_{quicksand,moving_sand,windy_ground},
 * mario_push_off_steep_floor, get_additive_y_vel_for_jumps all come from mario_step.c.) */
/* ---- audio: Mario's voice (Phase 3). The kernel's voice-bank sounds map to MM VO sfx
 * whose SAMPLES the build swapped for Mario clips (Fierce Deity's bank -- form offset 0,
 * endgame-only donor; documented tradeoff: FD grunts in Mario's voice). Terrain/foley
 * banks stay silent for now (MM's own foley plays via the puppeted player). ---- */
#define DSCE_VOICE_JUMP 0    /* yah/wah/hoo jump grunts  -> VO_LI_SWORD_N  */
#define DSCE_VOICE_SHOUT 1   /* yahoo / waha-yippee      -> VO_LI_SWORD_L  */
#define DSCE_VOICE_HOOHOO 2  /* double-jump hoohoo       -> VO_LI_AUTO_JUMP */
#define DSCE_VOICE_HURT 3    /* uh/oof/attacked          -> VO_LI_DAMAGE_S */
#define DSCE_VOICE_FALL 4    /* waaaooow / whoa          -> VO_LI_FALL_L   */
extern void Dsce_AdapterPlayVoice(int kind);

/* terrain foley: SM64 bakes the terrain type into the id's low 3 bits
 * (terrainSoundAddend); we mask to the FAMILY and let MM's surface system
 * (floorSfxOffset) supply the material -- that's the entire point. */
#define DSCE_FOLEY_JUMP 0    /* 0x00-0x07 -> NA_SE_PL_JUMP_GROUND + surface  */
#define DSCE_FOLEY_LAND 1    /* 0x08-0x0F -> NA_SE_PL_LAND_GROUND + surface  */
#define DSCE_FOLEY_STEP 2    /* 0x10-0x17 -> NA_SE_PL_WALK_GROUND + surface  */
#define DSCE_FOLEY_BODYHIT 3 /* 0x18-0x1F -> NA_SE_PL_BODY_HIT               */
#define DSCE_FOLEY_SWIM 4    /* 0x33      -> NA_SE_PL_SWIM                   */
#define DSCE_FOLEY_BONK 5    /* 0x42/0x45 -> NA_SE_PL_BOUND                  */
#define DSCE_FOLEY_HEAVY 6   /* 0x60-0x67 -> NA_SE_PL_BOUND (ground pound)   */
#define DSCE_FOLEY_SPLASH 7  /* 0x30-0x32 -> NA_SE_EV_DIVE_INTO_WATER        */
#define DSCE_FOLEY_SPIN 8    /* 0x37/0x38 -> swing whoosh (pound/twirl windup) */
extern void Dsce_AdapterPlayFoley(int kind);
extern void Dsce_AdapterPlayMsfx(int key);

void play_sound(s32 soundBits, f32* pos) {
    s32 bank = (soundBits >> 28) & 0xF;
    s32 soundID = (soundBits >> 16) & 0xFF;
#if DSCE_XTEST
    { /* [DSCE XTEST R3] raw SM64-space sound request stream (soundBits, sandbox tick) */
        extern void Dsce_Log(const char*, s32, s32, s32, s32);
        extern u32 Dsce_XtestTick(void);
        Dsce_Log("snd", soundBits, (s32)Dsce_XtestTick(), 0, 0);
    }
#endif

    /* [DSCE MSFX] PC parity: on PC, SM64's own audio engine renders every request.
     * Here every kernel-reachable soundBits maps 1:1 to a MINTED sound -- the real SM64
     * sample(s), pre-rendered exactly as 00_sound_player.s performs that id (same
     * notes/pitches/velocities) and compiled into MM's samplebank. The lookup lives in
     * the MM-side adapter (it needs the NA_SE enums); unknown ids stay silent. */
    Dsce_AdapterPlayMsfx((bank << 8) | soundID);
}
void stop_sound(u32 soundBits, f32* pos) {
}
void set_sound_moving_speed(u8 bank, u8 speed) {
}
void raise_background_noise(s32 a) {
}
void lower_background_noise(s32 a) {
}
void play_cap_music(u16 seqArgs) {
}
void stop_cap_music(void) {
}
void fadeout_cap_music(void) {
}
void play_infinite_stairs_music(void) {
}
void play_shell_music(void) {
}
void stop_shell_music(void) {
}
struct Object* mario_get_collided_object(struct MarioState* m, u32 interactType) {
    return NULL; /* no SM64 object collisions in MM (interaction is MM-side) */
}

/* ---- save file / camera / level / misc ---- */
u32 save_file_get_flags(void) {
    return 0;
}
s32 save_file_get_total_star_count(s32 fileIndex, s32 minCourse, s32 maxCourse) {
    return 0;
}
s32 save_file_get_cap_pos(Vec3s capPos) {
    return FALSE;
}
void set_camera_mode(struct Camera* c, s16 mode, s16 frames) {
}
void set_camera_shake_from_hit(s16 shake) {
}
s16 level_trigger_warp(struct MarioState* m, s32 warpOp) {
    return 0;
}
void load_level_init_text(u32 arg) {
}
void print_text_fmt_int(s32 x, s32 y, const char* str, s32 n) {
}
struct Object* spawn_object(struct Object* parent, s32 model, const void* behavior) {
    return NULL;
}
void spawn_wind_particles(s16 pitch, s16 yaw) {
}

/* ---- animation plumbing: REAL data (Phase 2). gDsceMarioAnimTable is generated at build
 * time from the user's SM64 ROM extraction (gen_mario_anims.py). set_mario_animation reads
 * list->bufTarget BEFORE calling us, so we must copy INTO the fixed buffer, never swap the
 * pointer. Our Animation structs carry absolute pointers -> always return FALSE (no rebase).
 * Missing ids keep the fake anim and are counted (the suite asserts the count stays 0). */
extern const struct Animation* const gDsceMarioAnimTable[];
extern const int gDsceMarioAnimTableLen;
u32 gDsceAnimFallbacks = 0;

s32 load_patchable_table(struct DmaHandlerList* list, s32 index) {
    struct Animation* buf = (struct Animation*) list->bufTarget; /* bufTarget is void* */
    const struct Animation* a = NULL;
    if ((index >= 0) && (index < gDsceMarioAnimTableLen)) {
        a = gDsceMarioAnimTable[index];
    }
    if (a != NULL) {
        *buf = *a;
    } else {
        gDsceAnimFallbacks++;
        buf->flags = 0;
        buf->animYTransDivisor = 1;
        buf->startFrame = 0;
        buf->loopStart = 0;
        buf->loopEnd = 2;
        buf->unusedBoneCount = 0;
        buf->values = sDsceFakeAnimValues;
        buf->index = sDsceFakeAnimIndex;
        buf->length = 0;
    }
    return FALSE;
}
s16 geo_update_animation_frame(struct AnimInfo* obj, s32* accelAssist) {
    return 0;
}
void* segmented_to_virtual(const void* addr) {
    return (void*) addr;
}
s32 retrieve_animation_index(s32 frame, u16** attributes) {
    return 0;
}

/* ---- host-libc leftovers in the driver's test harness (never run on N64) ---- */
char* getenv(const char* name) {
    return NULL;
}
unsigned long strtoul(const char* s, char** end, int base) {
    return 0;
}
